### ISSUE TITLE
为什么过段时间就报错“请求内容过大，请删除部分对话或关闭连续对话！”

### ISSUE THREAD

**Issue by xiaociliang** [xqdoo00o/chatgpt-web#103]
为什么过段时间就报错“请求内容过大，请删除部分对话或关闭连续对话！”。它POST内容，100个字符都不到。清空一下浏览器缓存，再刷新它又可以了。

**Comment by xqdoo00o** [comment]
默认4ktoken限制，开启25条内连续对话，也就是说你历史25条内的都会被post发出去，会超出4k token限制。
你可以在右上角设置里把连续会话上下文 改为0，就好了

**Comment by xiaociliang** [comment]
这个POST内容很短吧，100个字符都不到，应该不是4ktoken限制的问题吧。

**Comment by xiaociliang** [comment]
![QQ浏览器截图20230721205436](https://github.com/xqdoo00o/chatgpt-web/assets/6829332/dfa25b05-b8e9-404c-ba58-4ed3be27f00d)
清空浏览器缓存后它就又可以了

**Comment by xqdoo00o** [comment]
嗯，那也可能是api抽风了
