### ISSUE TITLE
how ???

### ISSUE THREAD

**Issue by CycloneAddons** [xqdoo00o/chatgpt-web#105]
How i can  make it if the ai response contain a link of image it automatically show in webpage with other text like

this is ai response
```
Sure, here is your image 
https://www.bhg.com/thmb/xktLhC5JenSEcBglx37FSUumqTo=/1244x0/filters:no_upscale():strip_icc()/stone-walkway-leading-garden-ccab4820-64cc37892feb45a58001bc53f6ba7aeb.jpg
````

i want 

```
Sure, here is your image 
<img src="https://www.bhg.com/thmb/xktLhC5JenSEcBglx37FSUumqTo=/1244x0/filters:no_upscale():strip_icc()/stone-walkway-leading-garden-ccab4820-64cc37892feb45a58001bc53f6ba7aeb.jpg>
```
i mean directly imAGE SHOW HERE

**Comment by CycloneAddons** [comment]
PLEASEEE TELL
ME

**Comment by xqdoo00o** [comment]
add prompt "response the img with markdown format"

**Comment by CycloneAddons** [comment]
Like ?? Can u give me example

**Comment by xqdoo00o** [comment]
`"Your original input", response the image with markdown format`
html element image does not directly show, but markdown image does

**Comment by CycloneAddons** [comment]
THANKS IT IS SENDING BUT IMG SIZE IS TOO BIG. IT CAPTURE HOLE SCREEN

**Comment by CycloneAddons** [comment]
is there any way to send response when the image link ready of delay for 10s 
i am generating image from replicate && also how i can execute it if the any word about imagine , generate i mean it automatically understand it is asking for image because generate , IMAGINE  can use for other thing

**Comment by xqdoo00o** [comment]
> THANKS IT IS SENDING BUT IMG SIZE IS TOO BIG. IT CAPTURE HOLE SCREEN ANY WAY TO MAKE ITS SIZE NORMAL WITH CSS

Test the img default automatic width, if the image exceed whole window width, it shows in window width, if not, it shows original width.
What is your meaning of SIZE NORMAL ? How to define NORMAL?

**Comment by CycloneAddons** [comment]
I just want to know that from which line of code convert markdown format to append image

**Comment by CycloneAddons** [comment]
And how the code generated by gpt shown in code block format

**Comment by xqdoo00o** [comment]
> I just want to know that from which line of code convert markdown format to append image

It's a js library named "markdown-it"
