### ISSUE TITLE
目前是查询余额是有问题了吗？Keys 是能正常使用，就是查余额查不了

### ISSUE THREAD

**Issue by gsfilm** [xqdoo00o/chatgpt-web#106]

**Comment by xqdoo00o** [comment]
需要session key来查询了，只使用api key查询不了了。

**Comment by ysmintor** [comment]
> 需要session key来查询了，只使用api key查询不了了。

有办法解决吗？session key 只能登陆账号产生？

**Comment by xqdoo00o** [comment]
open browser console, login https://platform.openai.com/account/usage
find the `credit_grants` in console network tab, look at the requqest headers `Authorization`, the `sess-***` is that session key.
but the operation is too complex and useless, in that page you could just directly get the usage data.

**Comment by xqdoo00o** [comment]
Removed check bill button
