### ISSUE TITLE
Hi brother 

### ISSUE THREAD

**Issue by yswlww** [xqdoo00o/chatgpt-web#108]
May i know where i can modify the unusable model like the GPT-4-browsing? also i would like to add other's model, where i can add?

**Comment by xqdoo00o** [comment]
Here https://github.com/xqdoo00o/chatgpt-web/blob/main/index.html#L2361

**Comment by yswlww** [comment]
after i have modify the models, when i visit the page, the old models still here, and i need to press control F4 each time, then can see the new models

**Comment by xqdoo00o** [comment]
> After i have modified the models at L2361, when i visit the page, the old models still here, and i need to press control F5 each time, then can see the new models

Do you setup the pwa? if so just force-refresh in sidebar or add version number in sw.js

**Comment by yswlww** [comment]
> > After i have modified the models at L2361, when i visit the page, the old models still here, and i need to press control F5 each time, then can see the new models
> 
> Do you setup the pwa? if so just force-refresh in sidebar or add version number in sw.js

No i haven't setup the pwa, just modified the models there in L2361

**Comment by xqdoo00o** [comment]
> > > After i have modified the models at L2361, when i visit the page, the old models still here, and i need to press control F5 each time, then can see the new models
> > 
> > 
> > Do you setup the pwa? if so just force-refresh in sidebar or add version number in sw.js
> 
> No i haven't setup the pwa, just modified the models there in L2361

should not, just click force-refresh button in sidebar or clear browser cache

**Comment by yswlww** [comment]
thanks bro, i found it caused by the chrome, thanks
