### ISSUE TITLE
navigator.serviceWorker.register这个用来做什么的？

### ISSUE THREAD

**Issue by xiaociliang** [xqdoo00o/chatgpt-web#112]
navigator.serviceWorker.register这个用来做什么的？有哪些地方用到这个？不能直接用【本地存储localstorage】，为什么还要再搞一个？

**Comment by xqdoo00o** [comment]
> navigator.serviceWorker.register这个用来做什么的？有哪些地方用到这个？不能直接用【本地存储localstorage】，为什么还要再搞一个？

PWA需要，没PWA的话，其实你可以手动删掉相关代码`registerSW`
