### ISSUE TITLE
语音合成的自动朗读 与  语音识别的保持监听，冲突了

### ISSUE THREAD

**Issue by UerLink** [xqdoo00o/chatgpt-web#116]
“自动朗读”的内容被识别到文本框里面去了，能否加一个“自动朗读”时关闭“保持监听” 播放完后再开启的功能。

虽然上面的问题，带耳机可以解决。哈哈哈

**Comment by xqdoo00o** [comment]
这个你试下开下麦克的回声消除和降噪吧，或者n卡的话用RTX voice软件消除音箱声
