### ISSUE TITLE
大佬可以优化一下Windows、安卓手机的兼容性吗

### ISSUE THREAD

**Issue by Juson666** [xqdoo00o/chatgpt-web#117]
目前Windows电脑Chrome浏览器需要开启VPN才能使用语音、安卓手机Chrome开了VPN也不行，IOS没问题。希望大佬能优化Windows、安卓的兼容~~

**Comment by xqdoo00o** [comment]
电脑应该是你们那Q太高了，我这里不用vpn也行。安卓端可以去权限管理 检查下有没有给予语音相关的权限

**Comment by Juson666** [comment]
有给语音权限的，而且我测试IOS可以的，就安卓不行。安卓可以语音朗读但不能语音识别进行录音

![c266bd85b03d0c89f6cd7a464c2f06a](https://github.com/xqdoo00o/chatgpt-web/assets/139359951/bd620db5-0b3b-4c7c-b974-31719932482a)

**Comment by xqdoo00o** [comment]
那你安卓chrome试试官方demo网址：https://www.google.com/intl/en/chrome/demos/speech.html
看看可以识别到吗

**Comment by xqdoo00o** [comment]
> 有给语音权限的，而且我测试IOS可以的，就安卓不行。安卓可以语音朗读但不能语音识别进行录音
> 
> ![c266bd85b03d0c89f6cd7a464c2f06a](https://user-images.githubusercontent.com/139359951/272510230-bd620db5-0b3b-4c7c-b974-31719932482a.jpg)

语音权限指的是安卓系统设置里的应用权限管理，在里面看下chrome的权限

**Comment by Juson666** [comment]
系统也有给语音权限

![0b299a87849c808781fce581f29f271](https://github.com/xqdoo00o/chatgpt-web/assets/139359951/785ec8d4-3c6f-4989-ba00-80bfb5370c77)

**Comment by Juson666** [comment]
> 那你安卓chrome试试官方演示网址：https://www.google.com/intl/en/chrome/demos/speech.html 看看可以识别到吗

手机上这个好像也不能录音，说话没反应

**Comment by Juson666** [comment]
> 那你安卓chrome练习官方演讲网址：https://www.google.com/intl/en/chrome/demos/speech.html 看看可以识别到吗

这个也好像不能录音

**Comment by xqdoo00o** [comment]
> > 那你安卓chrome练习官方演讲网址：https://www.google.com/intl/en/chrome/demos/speech.html 看看可以识别到吗
> 
> 这个也好像不能录音

那就是你系统或者浏览器问题了，官方应该可以的
