### ISSUE TITLE
暴露接口 和 API KEY

### ISSUE THREAD

**Issue by Juson666** [xqdoo00o/chatgpt-web#120]
![image](https://github.com/xqdoo00o/chatgpt-web/assets/139359951/484b14bb-f597-441e-9a1f-0b2d04a005ea)

请大佬帮忙修复~

**Comment by xqdoo00o** [comment]
这个只要用https，别人是看不到的，建议了解下https的原理。如果也不想在控制台看到，可以参考nginx配置，把api key放服务端。
