### ISSUE TITLE
想简单的自动保存进数据库怎么弄呢?

### ISSUE THREAD

**Issue by Daqiv** [xqdoo00o/chatgpt-web#122]
你好大神.我是小白,真厉害!
不是很懂,怎么做有选项可以做数据持久层,比如发送的消息,接受到的消息怎么写入数据库,或者发送REST进自己的php接口写入数据库?
仅仅是好奇,马上就关闭issues, 嘻嘻嘻~

**Comment by xqdoo00o** [comment]
这个是纯前端项目，所有数据都是存入浏览器的localstorage的，你可以自己搞一个服务端，调接口保存
