### ISSUE TITLE
语音功能丢失！

### ISSUE THREAD

**Issue by suzhouhu** [xqdoo00o/chatgpt-web#123]
![图片](https://github.com/xqdoo00o/chatgpt-web/assets/23079693/380420c5-0cdb-4e86-b2aa-a927040defa0)
点击发音，没有任何声音！

**Comment by xqdoo00o** [comment]
是之前可以，现在不行么？是的话应该是部分地区和isp把接口封了。
你可以试试用edge浏览器右键大声朗读，看行不行，不行的话就是isp和地区的问题。

**Comment by suzhouhu** [comment]
之前可以，现在不行了，用edge浏览器，点击右键大声朗读，能发声的！！

**Comment by xqdoo00o** [comment]
> 之前可以，现在不行了，用edge浏览器，点击右键大声朗读，能发声的！！

右上角语音合成那里设置是什么

**Comment by suzhouhu** [comment]
原来只能在edge浏览器，在火狐就不行！

**Comment by xqdoo00o** [comment]
> 原来只能在edge浏览器，在火狐就不行！

已修复，可更新最新版试试

**Comment by suzhouhu** [comment]
这个应该只支持edge 浏览器！在火狐不行

**Comment by xqdoo00o** [comment]
最新版本也不行吗

**Comment by suzhouhu** [comment]
最新版本在火狐还是没有发音！

**Comment by xqdoo00o** [comment]
> 最新版本在火狐还是没有发音！

刚又更新了下， 请在尝试下

**Comment by suzhouhu** [comment]
可以了！
