### ISSUE TITLE
微信打开网页，麦克风输入问题

### ISSUE THREAD

**Issue by tomatocuke** [xqdoo00o/chatgpt-web#128]
请教，微信打开网页，获取麦克风权限后，无法生成文字写入输入框，这个是什么问题？

**Comment by xqdoo00o** [comment]
可能是网络问题，开启科学上网再试试

**Comment by tomatocuke** [comment]
我是开发者， 前后端我都会。    
现在的情况是：浏览器打开网页OK，语音会产生文字进输入框。  微信打开网页，获取语音权限，但是不产生文字进入输入框。
你自己搭建的没有这个问题么？

**Comment by xqdoo00o** [comment]
没有，更新下微信版本或者开启科学上网试试
