### ISSUE TITLE
引用文件cdn出现问题

### ISSUE THREAD

**Issue by tomatocuke** [xqdoo00o/chatgpt-web#130]
我本地今天引用的 https://cdn.staticfile.org  前缀的文件都跨域禁止了，文件是在的。

提示` has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://xxx.xxx' that is not equal to the supplied origin.`

有意思，报错的  header has a value  https://xxx.xxx 这个各种各样，我进去看好像都是用的你这个项目的，但都进不去了。

我都换成 https://cdnjs.cloudflare.com/ajax/libs 了。

**Comment by xqdoo00o** [comment]
参考https://github.com/staticfile/static/issues/662
应该是他们的bug

**Comment by tomatocuke** [comment]
哈哈，看了。可真逗，还没修复
