### ISSUE TITLE
css和js提示跨域限制，请问怎么解决？

### ISSUE THREAD

**Issue by yolend88** [xqdoo00o/chatgpt-web#134]
Access to CSS stylesheet at 'http://cdn.staticfile.org/github-markdown-css/5.3.0/github-markdown-light.min.css' from origin 'http://chat.fast100.top' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by famousprince** [comment]
https://github.com/xqdoo00o/chatgpt-web/blob/main/index.html

将该文件内的 `cdn.staticfile.org` 替换为 `s4.zstatic.net/ajax/libs`

**Comment by xqdoo00o** [comment]
更新最新版也可，全https了
