### ISSUE TITLE
大神好！希望能夠支持Gemini Pro

### ISSUE THREAD

**Issue by ggllqzy** [xqdoo00o/chatgpt-web#135]
烦请有空研究下希望能增加Gemini Pro  谢谢

**Comment by xqdoo00o** [comment]
pro是免费的吗，是的话如何申请

**Comment by ggllqzy** [comment]
> pro是免费的吗，是的话如何申请

免费的Google Ai 用户自己申请key就能用，希望您能把Gemini的接口也接到您的对话面板上，对比了很多这个Ai面板，感觉您开发的最实用，简约而功能强大。

Gemini接口参考项目
1、https://github.com/Jazee6/cloudflare-ai-web

2、https://github.com/babaohuang/GeminiProChat/blob/main/README_cn.md

**Comment by xqdoo00o** [comment]
好了
