### ISSUE TITLE
语音输入问题

### ISSUE THREAD

**Issue by owcowc** [xqdoo00o/chatgpt-web#137]
你好，请问我尝试语音输入，使用的是“系统语言”，说话之后没有任何输入的结果，请问是设置的问题吗？浏览器的麦克风权限也打开了。另外，能够把语音输入功能增加一个whisper的接口选线，谢谢！

**Comment by xqdoo00o** [comment]
whisper不支持实时stream输入，也就是必需输入完一段语音才可以识别

**Comment by xqdoo00o** [comment]
不是设置的问题，可能是系统接口被你那的地区运营商 屏蔽了，你用全局代理模式试试

**Comment by owcowc** [comment]
> 不是设置的问题，可能是系统接口被你那的地区运营商 屏蔽了，你用全局代理模式试试

谢谢，我用PC挂全局成功了，请问安卓手机也有可以用吗？

**Comment by xqdoo00o** [comment]
只要吃chrome系的浏览器就行，微信都行

**Comment by xqdoo00o** [comment]
已添加whisper，就是需要手动停止语音

**Comment by owcowc** [comment]
> 已添加whisper，就是需要手动停止语音开始识别

谢谢
