### ISSUE TITLE
how can i add spanish language?

### ISSUE THREAD

**Issue by jonathanchourio** [xqdoo00o/chatgpt-web#15]
im testing but i want to know if is possible add spanish voices to the chinese and english list.

**Comment by xqdoo00o** [comment]
Of course, find the string `zh-|en-` in html file, change to `zh-|en-|es-`.

If you mean speech recognition spanish, add an es lang list 
from `view-source:https://www.google.com/intl/en/chrome/demos/speech.html`
![image](https://user-images.githubusercontent.com/12299238/228534838-9255ff62-1a51-427e-8e46-135741e0d372.png)
to the  `let langs` array in html file
