### ISSUE TITLE
希望支持页面自定义API HOST

### ISSUE THREAD

**Issue by alitrack** [xqdoo00o/chatgpt-web#16]
这个项目很赞

如果可以把反代的设置也放在API Key的上方就更好了，这样连Nginx都省了，只需要一个最普通的HTTP Server就可以了

**Comment by xqdoo00o** [comment]
这是不可能的，反代必须要后端server反代，前端无法反代

**Comment by alitrack** [comment]
可能你误解我的意思了

我们可以使用类似cf的service来做反代， 这样如果把这个项目部署在国内，就不用TZ了

这是个参考， https://github.com/alitrack/openai_proxy

**Comment by xqdoo00o** [comment]
哦，意思是加个配置api地址的选项是吧，html跟接口分离了

**Comment by alitrack** [comment]
是的，如果坚持要用nginx，则可以把api地址设置为nginx服务器的地址这样灵活些，当然我是直接修改html了

**Comment by xqdoo00o** [comment]
> 是的，如果坚持要用nginx，则可以把api地址设置为nginx服务器的地址这样灵活些，当然我是直接修改html了

好了

**Comment by alitrack** [comment]
谢谢！
