### ISSUE TITLE
如何显示图像？

### ISSUE THREAD

**Issue by suzhouhu** [xqdoo00o/chatgpt-web#17]
![image](https://user-images.githubusercontent.com/23079693/228710371-124dc389-446d-45ab-8eec-d8c5be8f9112.png)

**Comment by xqdoo00o** [comment]
应该是可以的，你在图像那点一下右键新标签页打开，看下打得开不

**Comment by suzhouhu** [comment]
刘鹄中
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xqdoo00o/chatgpt-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xqdoo00o/chatgpt-web] 如何显示图像？ (Issue #17)





 
应该是可以的，你在图像那点一下右键新标签页打开，看下打得开不

**Comment by suzhouhu** [comment]
![image](https://user-images.githubusercontent.com/23079693/228713365-eae42bfb-d58d-4a14-b21a-b81f2a4c6dd1.png)

**Comment by xqdoo00o** [comment]
这个是原始数据中给的错误的图片地址导致的

**Comment by suzhouhu** [comment]
![image](https://user-images.githubusercontent.com/23079693/229049696-13087ccb-8b5b-4fd0-8283-498985b9dcfc.png)
有没有哪位成功显示出图片的？发出来看看。我在怀疑他就不能呈现图像！或者设置问题

**Comment by xqdoo00o** [comment]
发”发个猫猫图“
![image](https://user-images.githubusercontent.com/12299238/229050891-8e72dce0-928a-4955-a1b9-c220d9f57f53.png)
