### ISSUE TITLE
利用socat出现ssl握手错误

### ISSUE THREAD

**Issue by 2168028160** [xqdoo00o/chatgpt-web#18]
nginx配置文件
```
	location ^~ /v1 {
		proxy_pass https://127.0.0.1:8443;
		proxy_set_header Host api.openai.com;
		proxy_set_header  Authorization "Bearer sk-xxx";
		proxy_pass_header Authorization;
		proxy_buffering off;
	}
	
	location / {
		root /usr/share/nginx/html;
		index index.html;
	}
```
Nginx错误日志
`2023/03/30 16:03:55 [error] 17244#17244: *2 SSL_do_handshake() failed (SSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure) while SSL handshaking to upstream, client: 10.167.237.172, server: , request: "POST /v1/chat/completions HTTP/1.1", upstream: "https://127.0.0.1:8443/v1/chat/completions", host: "10.167.237.118", referrer: "http://10.167.237.118/"`

有大佬知道解决方案吗？

**Comment by xqdoo00o** [comment]
socat命令是怎么写的

**Comment by 2168028160** [comment]
socat TCP4-LISTEN:8443,reuseaddr,fork PROXY:proxy.nic.xxx.com:api.openai.com:443,proxyport=8080,proxyauth=user:passwd

**Comment by xqdoo00o** [comment]
应该是昨天接口更新tls1.3导致的，socat貌似不支持tls1.3

**Comment by xqdoo00o** [comment]
第二个是对的，如果在国内的话，curl走代理了，就是nginx的proxy_pass 不支持前置代理。

**Comment by 2168028160** [comment]
大佬有解决方案吗。。。

**Comment by 2168028160** [comment]
不使用nginx,使用caddy可以实现吗？

**Comment by xqdoo00o** [comment]
> 不使用nginx,使用caddy可以实现吗？

caddy好像可以，不过还没正式发布版本，要等这个[PR](https://github.com/caddyserver/caddy/pull/5369)合并后发的新版本，也就是2.6.5及之后的版本。
也可以用Actions里[最新编译](https://github.com/caddyserver/caddy/actions/runs/4572474099)的版本。
就支持使用http_proxy和https_proxy环境变量里的代理了
比如
```
export http_proxy=http://127.0.0.1:10809
export https_proxy=http://127.0.0.1:10809
```
再运行caddy

**Comment by xqdoo00o** [comment]
> 大佬有解决方案吗。。。

你参考下最新的nginx配置，加两行就好了，socat配置不变
