### ISSUE TITLE
按文档中的把API KEY输入，但是还是报API KEY错误

### ISSUE THREAD

**Issue by jimmieyuan** [xqdoo00o/chatgpt-web#2]
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
已经按文档中的把API KEY输入，但是还是报API KEY错误，请问这个要如何解决？
![Snipaste_2023-03-09_08-45-03](https://user-images.githubusercontent.com/125749873/223885900-e11b583b-fdbe-4e39-acf3-584c74fbd9d7.png)

**Comment by xqdoo00o** [comment]
目前看不出来啥问题，Nginx是哪个版本的

**Comment by jimmieyuan** [comment]
版本是：nginx/1.15.8

**Comment by xqdoo00o** [comment]
升级下，到1.20以上试试

**Comment by xqdoo00o** [comment]
请使用最新版本，应该不会有问题了，nginx要加一行配置 `proxy_buffering off;`

**Comment by jimmieyuan** [comment]
谢谢，已经用其代理的方式解决了，这种反代方式好像目前很难使用了
