### ISSUE TITLE
ios 手机下 开着自动朗读但是不会自动朗读

### ISSUE THREAD

**Issue by as882301** [xqdoo00o/chatgpt-web#20]
ios 手机下 开着自动朗读但是不会自动朗读  pc 是可以的

**Comment by xqdoo00o** [comment]
ios可能比较慢，因为是惟一不支持流式音频的平台，要等音频加载结束才开始播放。
可以等一会再听听有没有播放。

**Comment by xqdoo00o** [comment]
那是个bug了，明天检查下

**Comment by xqdoo00o** [comment]
这个是ios的问题，可以在safari偏好设置里，允许这个网页的自动播放媒体。不然自动播放的时候必须要手动点一个按钮之类的才能播放。

**Comment by as882301** [comment]
好的 谢谢 明白了 原来是这个问题 ！
