### ISSUE TITLE
help me plz

### ISSUE THREAD

**Issue by ddluci** [xqdoo00o/chatgpt-web#21]
2023/03/31 15:53:01 [error] 724#4800: *65 SSL_do_handshake() failed (SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:SSL alert number 40) while SSL handshaking to upstream, client: 2.58.65.58, server: localhost, request: "POST /v1/chat/completions HTTP/1.1", upstream: "https://104.18.7.192:443/v1/chat/completions", host: "保密", referrer: "保密"

**Comment by xqdoo00o** [comment]
Plz use the newest nginx config in readme.
Especially add the two line
```
proxy_ssl_name api.openai.com;
proxy_ssl_server_name on;
```
