### ISSUE TITLE
服务器部署无法使用语音识别

### ISSUE THREAD

**Issue by yolend88** [xqdoo00o/chatgpt-web#22]
![image](https://user-images.githubusercontent.com/60383097/229186222-fbe680f7-70bd-4fed-8d41-274c0d376b0b.png)

自己的服务器部署，部署后，显示“当前浏览器不支持语音识别，请尝试更换浏览器或重新部署页面”

**Comment by xqdoo00o** [comment]
这个是浏览器不支持或者没https，用chrome系的+https

**Comment by xqdoo00o** [comment]
看别人说，
![image](https://user-images.githubusercontent.com/12299238/229258069-a34ed0e6-f54b-4840-bf55-11224f1854dd.png)
http的要每次都授权麦克风，并且实测新版本的chrome授不了http的权限了。
所以要部署https+chrome浏览器使用

**Comment by alitrack** [comment]
我可以使用麦克风了，但不知道咋用，刷新页面，可以点麦克风，但没有后续反应了，再按麦克风就没有反应了，再刷新，又是如此

**Comment by xqdoo00o** [comment]
有安装麦克风设备吗，允许网站的麦克风权限了吗，用下最新版的HTML有错误提示的

**Comment by alitrack** [comment]
- 权限是有的
<img width="352" alt="image" src="https://user-images.githubusercontent.com/20972179/229335117-fb2b0709-356d-4fa9-bff4-54e4c58e0051.png">
- 也显示在录音
<img width="104" alt="image" src="https://user-images.githubusercontent.com/20972179/229335150-1955e1b7-e042-4888-8ad6-e80057952564.png">

- 有时候是这个
<img width="265" alt="image" src="https://user-images.githubusercontent.com/20972179/229335168-6e8a4c06-15d1-49a5-8a50-bdb5ef902a17.png">

- 多数是没有反应


我用Voice Memos测试，是OK的

**Comment by xqdoo00o** [comment]
你试下谷歌官方[Demo](https://www.google.com/intl/en/chrome/demos/speech.html)行不行，
然后用的是啥浏览器呀

**Comment by alitrack** [comment]
更新到最新版本的Chrome，并且FQ后，chatgpt-web也可以了

**Comment by xqdoo00o** [comment]
> 更新到最新版本的Chrome，并且FQ后，chatgpt-web也可以了
> 
> 看了源代码，知道了，依赖Google的

可能是你那网络不行吧，我这不FQ，一样能用，不管是chrome还是edge

**Comment by kill136** [comment]
可能真的要翻墙，我这边翻墙才能识别

**Comment by xqdoo00o** [comment]
> 可能真的要翻墙，我这边翻墙才能识别

手机上edge或者chrome呢，我这不用翻都行
