### ISSUE TITLE
手机端左侧顶部的新建会话选项有bug

### ISSUE THREAD

**Issue by shellalumni** [xqdoo00o/chatgpt-web#25]
经常点击了没反应，偶尔有一次点开后不能返回主界面

还有三个小建议：
1、发送的内容都被压缩成一行了，特别是我要让它优化代码，太不好看了，希望能像官方那种保留发送内容格式。
2、有了"新建会话"选项感觉没必要在“发送”按钮边边存在“清空会话”，因为在手机端容易点到，太挤。或者修改为电脑端显示，手机端隐藏。
3、右侧选项是不是可以增加一个“恢复默认配置“

**Comment by xqdoo00o** [comment]
用最新版的HTML应该没这个bug了
1. 你可以在后面加一句 以markdown形式返回
2. 这个可以考虑下
3. 确实可以

**Comment by xqdoo00o** [comment]
新建会话的bug最新版本修复了应该

**Comment by shellalumni** [comment]
> 用最新版的HTML应该没这个bug了

测试了手机端还是一样问题：点击左侧顶部三条杠没反应。用的是iphone safari浏览器和微信里的浏览器。右侧倒是正常

> 你可以在后面加一句 以markdown形式返回

我指的是发送过去的代码内容挤在一行，不是接受到的内容

**Comment by xqdoo00o** [comment]
> > 用最新版的HTML应该没这个bug了
> 
> 测试了手机端还是一样问题：点击左侧顶部三条杠没反应。用的是iphone safari浏览器和微信里的浏览器。右侧倒是正常
> 
> > 你可以在后面加一句 以markdown形式返回
> 
> 我指的是发送过去的代码内容挤在一行，不是接受到的内容
> 
> BTW：要不要新增一个AI做图功能，哈哈

改好了

**Comment by shellalumni** [comment]
> > > 用最新版的HTML应该没这个bug了
> > 
> > 
> > 测试了手机端还是一样问题：点击左侧顶部三条杠没反应。用的是iphone safari浏览器和微信里的浏览器。右侧倒是正常
> > > 你可以在后面加一句 以markdown形式返回
> > 
> > 
> > 我指的是发送过去的代码内容挤在一行，不是接受到的内容
> > BTW：要不要新增一个AI做图功能，哈哈
> 
> 改好了

厉害了我的哥
