### ISSUE TITLE
windows server 2016，执行exe报错

### ISSUE THREAD

**Issue by fredzhu** [xqdoo00o/chatgpt-web#28]
windows server 2016版，英文系统
语句中有中文字符？

错误如下：

2023/04/06 13:50:10 [32m/go/pkg/mod/github.com/glebarez/sqlite@v1.7.0/migrator.go:310
[0m[33m[0.000ms] [34;1m[rows:-][0m SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "users" AND name = "idx_users_updated_at"
2023/04/06 13:50:10 decode config err: invalid character 'ï' looking for beginning of value

**Comment by xqdoo00o** [comment]
什么意思？
