### ISSUE TITLE
Possible to use Davinci

### ISSUE THREAD

**Issue by oleteacher** [xqdoo00o/chatgpt-web#33]
Hello friends. I would like to use your chatgpt-web for some classroom experiments.

Is it possible to support text-davinci-003?

Very nice project you have. Sorry I do not speak your language, please forgive my question in english.

Cheers!

**Comment by xqdoo00o** [comment]
Sorry but probably not，that's total different openai api if use text-davinci-003, and the cost is more expensive than gpt-3.5-turbo,
