### ISSUE TITLE
请教如何拆分流式数据

### ISSUE THREAD

**Issue by lzcmian** [xqdoo00o/chatgpt-web#34]
一般接口返回的数据式这样子的
`data: {"id":"chatcmpl-74nY49RucRFv2IE0csGi5svtMQpAF","object":"chat.completion.chunk","created":1681378132,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"role":"assistant"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-74nY49RucRFv2IE0csGi5svtMQpAF","object":"chat.completion.chunk","created":1681378132,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"你"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-74nY49RucRFv2IE0csGi5svtMQpAF","object":"chat.completion.chunk","created":1681378132,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"好"},"index":0,"finish_reason":null}]}`

我阅读您的代码，发现您使用 `value.split(/\n{2}/g)` 来拆分每一组数据，后续的代码我不太理解，我想知道如果content中包含了
`\n\n` 您程序是如何处理的？

非常感谢

**Comment by xqdoo00o** [comment]
content中的`\n`其实是被转义的`\n`，转义后才打印出字符`\n`，正则匹配的话要用`\\n`
不转义的话，打印出来会直接换行，而不是打印字符`\n`
据观察，接口返回数据里content内容里是不会直接换行的
所以不需要处理

**Comment by lzcmian** [comment]
我明白了，谢谢您的回答
