### ISSUE TITLE
对gpt提问后，如果相应的是代码，代码格式混乱，显示不全，如何解决

### ISSUE THREAD

**Issue by liruitai** [xqdoo00o/chatgpt-web#37]
![image](https://user-images.githubusercontent.com/52032312/233242387-da8d9ad3-8663-47b5-bd21-86b8f4ad1767.png)

**Comment by xqdoo00o** [comment]
这个是必现的吗，还是偶尔出现，可以提供下复现的提问吗

**Comment by liruitai** [comment]
cesium 如何旋转实体对象。
ps:把index.html换成 pull request里面那哥们的就好了

**Comment by liruitai** [comment]
只要回答代码包含js ，js部分全乱

**Comment by lingex** [comment]
有碰到类似的，shell脚本经常被识别成Markdown
![sp_2023-04-22_09-57-28](https://user-images.githubusercontent.com/13662998/233755898-ff9b9b98-6132-4c8e-9b96-79aeeac6d4be.jpg)

提问文本:
帮我写一个shell脚本，输入两个参数zone, portnum. 然后复制目录下的newzone文件夹命名为参数zone的值，接着修改复制好的文件夹中的所有.json文件：1.将文件中的newzone字符串修改为参数zone的值，2.将port:xxx(数字)修改为port:portnum的值

**Comment by xqdoo00o** [comment]
> 有碰到类似的，shell脚本经常被识别成Markdown ![sp_2023-04-22_09-57-28](https://user-images.githubusercontent.com/13662998/233755898-ff9b9b98-6132-4c8e-9b96-79aeeac6d4be.jpg)
> 
> 提问文本: 帮我写一个shell脚本，输入两个参数zone, portnum. 然后复制目录下的newzone文件夹命名为参数zone的值，接着修改复制好的文件夹中的所有.json文件：1.将文件中的newzone字符串修改为参数zone的值，2.将port:xxx(数字)修改为port:portnum的值

这个看起来像是代码部分没识别为markdown

**Comment by StoneLyu** [comment]
我出现了类似的问题，不仅仅是代码部分，正文部分也会出现乱码。
<img width="953" alt="image" src="https://user-images.githubusercontent.com/16559774/235029945-c9233be0-5201-4d0e-b0cf-67e34061c2aa.png">
我更新了28号00:45 commit的版本，有用nginx，用了HTTPS。
而且，只是国内的访问会出现乱码。部署在我的vps上，从国内访问出现乱码，从国外访问就是正常的😓

**Comment by xqdoo00o** [comment]
> 我出现了类似的问题，不仅仅是代码部分，正文部分也会出现乱码。 <img alt="image" width="953" src="https://user-images.githubusercontent.com/16559774/235029945-c9233be0-5201-4d0e-b0cf-67e34061c2aa.png"> 我更新了28号00:45 commit的版本，有用nginx，用了HTTPS。 而且，只是国内的访问会出现乱码。部署在我的vps上，从国内访问出现乱码，从国外访问就是正常的😓

看下设置里 回答质量是不是调的太大了

**Comment by StoneLyu** [comment]
> > 我出现了类似的问题，不仅仅是代码部分，正文部分也会出现乱码。 <img alt="image" width="953" src="https://user-images.githubusercontent.com/16559774/235029945-c9233be0-5201-4d0e-b0cf-67e34061c2aa.png"> 我更新了28号00:45 commit的版本，有用nginx，用了HTTPS。 而且，只是国内的访问会出现乱码。部署在我的vps上，从国内访问出现乱码，从国外访问就是正常的😓
> 
> 看下设置里 回答质量是不是调的太大了

卧槽，是的！调到中间就恢复了，还以为是个bug，抱歉😂
