### ISSUE TITLE
mjj这个源码是我目前觉得最好最牛逼的了。

### ISSUE THREAD

**Issue by byxiaoguai** [xqdoo00o/chatgpt-web#39]
感谢mjj 大佬更新目前功能最多的页面，修改起来还方便
隔壁 开源都是 ts vue 各种乱七八糟 npm 打包 头疼还要兼容 node 哎，果然原生用的舒服点。

**Comment by byxiaoguai** [comment]
在不同的平台浏览器  chunk.slice(6) 截取有点问题。
我这边直接手动改成  chunk.replace(/^data:/, "")  截取好点

**Comment by xqdoo00o** [comment]
谢谢支持，另外哪些平台浏览器有问题呢，看发的代码应该是跟slice等价的

**Comment by xqdoo00o** [comment]
谢谢，我研究下
