### ISSUE TITLE
html代码无法正常显示

### ISSUE THREAD

**Issue by eureka6** [xqdoo00o/chatgpt-web#40]
首先，代码框里是正常显示：
```
&nbsp; #这是一串代码
```
然后，markdown语法也正常显示：`&nbsp;`

但要是回答中出现无格式的：`&nbsp;`

就直接是个空格：` `

看前面的issues，是不是没有太好的解决办法呀？

最后，忍不住赞一下，大佬代码的可读性真的超级高，让我这个小白都能试着动手改一改：）

**Comment by xqdoo00o** [comment]
`&nbsp;`这个就是HTML的空格转义字符，所以是正常的
