### ISSUE TITLE
你好，聊天记录拖拽功能在手机上无法实现

### ISSUE THREAD

**Issue by mifen2** [xqdoo00o/chatgpt-web#41]
我想使用Sortable ，这个兼容性比较好，可惜水平有限，改了好久没改好，期待大佬出手

**Comment by xqdoo00o** [comment]
请更新最新版，移动端可以拖拽了。不过Sortable看起来还不错，我会研究下

**Comment by xqdoo00o** [comment]
用Sortable暂时找不到 把新会话拖拽到折叠文件夹下的方法，所以暂时先不管了

**Comment by mifen2** [comment]
一觉醒来发现这个已经实现了，非常感谢，太牛了，现在有个问题，就是如果在手机端，文件夹或者聊天记录太多，开始滚动的时候，滚动被阻止了，只能拖拽。

**Comment by mifen2** [comment]
> 用Sortable暂时找不到 把新会话拖拽到折叠文件夹下的方法，所以暂时先不管了

一觉醒来发现这个已经实现了，非常感谢，太牛了，现在有个问题，就是如果在手机端，文件夹或者聊天记录太多，开始滚动的时候，滚动被阻止了，只能拖拽。

**Comment by mifen2** [comment]
> > > 用Sortable暂时找不到 把新会话拖拽到折叠文件夹下的方法，所以暂时先不管了
> > 
> > 
> > 一觉醒来发现这个已经实现了，非常感谢，太牛了，现在有个问题，就是如果在手机端，文件夹或者聊天记录太多，开始滚动的时候，滚动被阻止了，只能拖拽。
> 
> 可以滚动了，长按一下才会拖拽

神速啊，兄弟你是专门做前端的吧，太厉害了！
