### ISSUE TITLE
你好大佬，请求太快提示频率太快，和api限额是真的限额吗

### ISSUE THREAD

**Issue by yuantouw** [xqdoo00o/chatgpt-web#47]
提示限额了，过几秒发起提问又有回复，这个是两次之间的发送间隔秒数导致，还是真的api限额哇

**Comment by xqdoo00o** [comment]
是啊，目前免费账户闲置每分钟三次

**Comment by yuantouw** [comment]
> 是啊，目前免费账号限制每分钟三次提问

啊哪行代码可以取消这个限制吗大佬，电脑端好像这个限制不频繁，手机端老是出现这个api限额呜呜呜呜呜呜呜

**Comment by xqdoo00o** [comment]
> > 是啊，目前免费账号限制每分钟三次提问
> 
> 啊哪行代码可以取消这个限制吗大佬，电脑端好像这个限制不频繁，手机端老是出现这个api限额呜呜呜呜呜呜呜

这个是官方限制的，也不是我限制的，电脑你一分钟内问的此说超过也会提示

**Comment by yuantouw** [comment]
好吧，谢谢你的回复

**Comment by yuantouw** [comment]
> > > 是啊，目前免费账号限制每分钟三次提问
> > 
> > 
> > 啊哪行代码可以取消删除这个限制吗大佬，电脑端好象这个限制不视频繁，手机端老是出现这个api限制呜呜呜呜呜呜呜
> 
> 这个是官方限制的，也不是我限制的，电脑你一分钟内问的次数超过也会提示

好吧，谢谢你的回复！
