### ISSUE TITLE
basic_auth一开启就报错

### ISSUE THREAD

**Issue by eureka6** [xqdoo00o/chatgpt-web#48]
大佬，配置了下面的东西后，Nginx的basic_auth一开启就报错
```
map $http_authorization $gptauth {
    default  $http_authorization;
    ""       "Bearer sb-your-token"; #这里改了
}
server {
    listen       80;
    server_name  example.com;
    gzip  on;
    gzip_min_length 1k;
    gzip_types text/event-stream;

    location ^~ /v1 {
        proxy_pass https://api.openai-sb.com/v1;   #这里改了
        proxy_set_header Host api.openai-sb.com;   #这里改了
        proxy_ssl_name api.openai-sb.com;   #这里改了
        proxy_ssl_server_name on;
        proxy_set_header Authorization $gptauth;
        proxy_pass_header Authorization;
        proxy_buffering off;
    }

    location / {
        alias /usr/share/nginx/html/;
        index index.html;
    }
}
```
开启basic_auth后，网页上提示`API密钥错误或失效，请检查API密钥！`
关掉basic_auth就又正常了

另外，我用的是别人代理的api，需要把nginx配置里的代理地址、请求头之类从`api.openai.com`改成`api.openai-sb.com`，还要把`sk-`开头的密钥改成了`sb-`开头的密钥。这没影响吧？

主要是关闭basic_auth就一切都正常。

**Comment by xqdoo00o** [comment]
你的basic_auth配置 放到单html配置里看能生效吗

**Comment by yuantouw** [comment]
location / {
        alias /usr/share/nginx/html/; #网站真实路径如：/www/wwwroot/www.xxxx.cn/
        index index.html;#更目录则填真实的inde.html或者index.php，看你自己文件是啥
    }

**Comment by eureka6** [comment]
> 你的basic_auth配置 放到单html配置里看能生效吗 location / {这里， 然后打开网页，输入账号密码能正常进去吗

这样的话，可以正常使用。

**Comment by xqdoo00o** [comment]
放到location ^~ /v1 {
里就不能用了吗

**Comment by eureka6** [comment]
是的

**Comment by xqdoo00o** [comment]
> 是的

我知道了。basic_auth也占用Authorization头，如果你不在前端设置api密钥使用的话，proxy_set_header Authorization 这后面改回之前的那个默认密钥。

**Comment by xqdoo00o** [comment]
可以参考最新文档加密HTML使用
