### ISSUE TITLE
你好大佬，语音播报怎么自定义排序呀，因为我在大陆默认第一个香港受众不多

### ISSUE THREAD

**Issue by yuantouw** [xqdoo00o/chatgpt-web#49]
<img width="780" alt="image" src="https://github.com/xqdoo00o/chatgpt-web/assets/73607554/f318b4db-f29d-407a-aabd-95cd1986801d">

**Comment by xqdoo00o** [comment]
下个版本会改一下默认的语音，你要自己改排序的话可以在[这里](https://github.com/xqdoo00o/chatgpt-web/blob/main/index.html#L2977)改

**Comment by yuantouw** [comment]
> 下个版本会改下默认的语音，你要自己改顺序的话可以在[这里](https://github.com/xqdoo00o/chatgpt-web/blob/main/index.html#L2977)改

好的感谢，如果能能支持中文和自定义排序更好(/狗头)

**Comment by xqdoo00o** [comment]
> > 下个版本会改下默认的语音，你要自己改顺序的话可以在[这里](https://github.com/xqdoo00o/chatgpt-web/blob/main/index.html#L2977)改
> 
> 好的感谢，如果能能支持中文和自定义排序更好(/狗头)

改成大陆在前了，可以更新下
