### ISSUE TITLE
PWA应用在iPhone底部不适配

### ISSUE THREAD

**Issue by gmugu** [xqdoo00o/chatgpt-web#50]
![59c8b6240688cb07e54e624175c39d5](https://github.com/xqdoo00o/chatgpt-web/assets/8317478/8c30500c-53f3-4568-a78c-29aab9bf12cd)
建议将iPhoneX以上的全面屏机型底部输入栏部分抬高一点

**Comment by xqdoo00o** [comment]
不太好改，涉及很多css😂
