### ISSUE TITLE
谢谢大佬，有个问题，就是不支持不是以SW开头的密钥

### ISSUE THREAD

**Issue by CattleZoe** [xqdoo00o/chatgpt-web#54]
我用的是微软的azure的endpoint，并使用cloudflare的works转换为类openai的请求，但是输入的密钥不是sw开头的密钥，类似:35ksdifusuqwqweqwfdrg353eqwefs这样的KEY，但是你的这个系统不支持， 我用chtgpt next web等其它几个webui都能正常使用。你做得很好，麻烦看看是哪里问题。

提示：API密钥错误或失效，请检查API密钥！

**Comment by xqdoo00o** [comment]
> 我用的是微软的azure的endpoint，并使用cloudflare的works转换为类openai的请求，但是输入的密钥不是sw开头的密钥，类似:35ksdifusuqwqweqwfdrg353eqwefs这样的KEY，但是你的这个系统不支持， 我用chtgpt next web等其它几个webui都能正常使用。你做得很好，麻烦看看是哪里问题。

微软的endpoint地址是什么，你在OpenAI接口填的是什么

**Comment by CattleZoe** [comment]
谢谢大佬回复，微软的endpoint是自定义的，类似这样：
https://xxx.openai.azure.com(xxx是自定义的应用名称)
但是我用了cloudflare的works做了转发，可以使任何webui访问azure的endpoint模仿openai的调用而webui不做修改（chatgpt next web等3个以上webui测试通过），openai的接口输入框填的是xxx.xxxx.com经过cloudflare works trigggle自定义的（测试可以用），我怀疑是不是你的系统过滤了非sw开头的密钥，但是azure的密钥不是以sw开头。
PS:你的前几个版本我用azure的endpont是没问题，今天看你升级了，越来越好了，很棒，谢谢你，但是就是有这个问题，

**Comment by xqdoo00o** [comment]
> 谢谢大佬回复，微软的endpoint是自定义的，类似这样： [https://xxx.openai.azure.com(xxx是自定义的应用名称)](https://xxx.openai.azure.com(xxx%E6%98%AF%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E5%BA%94%E7%94%A8%E5%90%8D%E7%A7%B0)) 但是我用了cloudflare的works做了转发，可以使任何webui访问azure的endpoint模仿openai的调用而webui不做修改（chatgpt next web等3个以上webui测试通过），openai的接口输入框填的是xxx.xxxx.com经过cloudflare works trigggle自定义的（测试可以用），我怀疑是不是你的系统过滤了非sw开头的密钥，但是azure的密钥不是以sw开头。 PS:你的前几个版本我用azure的endpont是没问题，今天看你升级了，越来越好了，很棒，谢谢你，但是就是有这个问题，

你打开浏览器的开发者工具，找到网络那一栏，提问下，看下completion这个post请求的标头和预览，和你cloudflare workers的域名是不是一致，可以打码截个图看看

**Comment by CattleZoe** [comment]
好的，刚换.com域名，换国内外服务器都有这个问题，这是截图
![ERROR1](https://github.com/xqdoo00o/chatgpt-web/assets/5591163/418f65e8-130b-4cf3-98c3-8ee626d11aba)
![ERROR2](https://github.com/xqdoo00o/chatgpt-web/assets/5591163/c6583825-6e71-4af5-b8dd-c14691e1e6b4)
![ERROR3](https://github.com/xqdoo00o/chatgpt-web/assets/5591163/cd1cc5a9-49e2-4ece-be51-09e680ac2d5c)

**Comment by xqdoo00o** [comment]
> 好的，刚换.com域名，换国内外服务器都有这个问题，这是截图 ![ERROR1](https://user-images.githubusercontent.com/5591163/239194027-418f65e8-130b-4cf3-98c3-8ee626d11aba.png) ![ERROR2](https://user-images.githubusercontent.com/5591163/239194033-c6583825-6e71-4af5-b8dd-c14691e1e6b4.png) ![ERROR3](https://user-images.githubusercontent.com/5591163/239194035-cd1cc5a9-49e2-4ece-be51-09e680ac2d5c.png)

要看post请求，这个是options请求。
post请求也截下图

**Comment by CattleZoe** [comment]
好的
![ERROR4](https://github.com/xqdoo00o/chatgpt-web/assets/5591163/debe5109-732f-4460-aba6-7e00047c0165)
![ERROR5](https://github.com/xqdoo00o/chatgpt-web/assets/5591163/75bf7e73-fdc8-4563-85e5-e35d39f95a31)
![ERROR6](https://github.com/xqdoo00o/chatgpt-web/assets/5591163/c6eefa6c-9ce5-4019-b55f-e0d1d6d0aedb)
![ERROR7](https://github.com/xqdoo00o/chatgpt-web/assets/5591163/7c974bbc-3e0b-49f9-8707-caa5fd919a73)

**Comment by xqdoo00o** [comment]
> 好的 ![ERROR4](https://user-images.githubusercontent.com/5591163/239196989-debe5109-732f-4460-aba6-7e00047c0165.png) ![ERROR5](https://user-images.githubusercontent.com/5591163/239196992-75bf7e73-fdc8-4563-85e5-e35d39f95a31.png) ![ERROR6](https://user-images.githubusercontent.com/5591163/239196995-c6eefa6c-9ce5-4019-b55f-e0d1d6d0aedb.png) ![ERROR7](https://user-images.githubusercontent.com/5591163/239197002-7c974bbc-3e0b-49f9-8707-caa5fd919a73.png)
> 
> 另外你的api key是写在cloudflare worker代码里的吗，网页设置里有写吗
> 
> 不是的没有写任何敏感信息在workers

这个返回是200呀，还报错吗？
标头右边的负载和响应都分别是啥

**Comment by xqdoo00o** [comment]
另外如果说你前几个版本可以用，这个版本不行的话，可以改下html代码，把代码里`credentials: "omit"`都删掉看下有没有用

**Comment by CattleZoe** [comment]
去掉credentials: "omit"可以了哈，谢谢！！！！！！！！！！！！11

**Comment by xqdoo00o** [comment]
你更新下最新版再试试

**Comment by xqdoo00o** [comment]
> 去掉credentials: "omit" 可以了一下，但是不稳定啊，又不行了

是刷新完就不行，还是一直又不行了。开pwa了吗

**Comment by CattleZoe** [comment]
刷新一下，输入一句话，正常回复，然后报错了

**Comment by CattleZoe** [comment]
在你的https://xqdoo00o.github.io/chatgpt-web/ 这个上测试也是这样

**Comment by xqdoo00o** [comment]
> 刷新一下，输入一句话，正常回复，然后报错了， 最新版干脆又恢复原样了提示访问接口失败，请检查接口

那你对比下正常的和错误的completions的post和options请求，看标头一样吗

**Comment by CattleZoe** [comment]
要不你给我一个邮箱，我申请一个临时的endpoint和key给你测试一下

**Comment by xqdoo00o** [comment]
> 要不你给我一个邮箱，我申请一个临时的endpoint和key给你测试一下



> 要不你给我一个邮箱，我申请一个临时的endpoint和key给你测试一下

好 xqdoo00o@gmail.com

**Comment by CattleZoe** [comment]
已经发给你了，请收！

**Comment by xqdoo00o** [comment]
> 已经发给你了，请收！

收到了，设置里OpenAI接口应该填cf worker的地址吧

**Comment by CattleZoe** [comment]
是的

**Comment by xqdoo00o** [comment]
> 是的

好了，你用最新版试试

**Comment by CattleZoe** [comment]
> > 是的
> 
> 好了，你用最新版试试，忘了容错了

太棒了，效率真高，高手！！！，ps：那个“检查API额度”的报错也需要修改一下

感谢你的回复！！！

**Comment by xqdoo00o** [comment]
> > > 是的
> > 
> > 
> > 好了，你用最新版试试，忘了容错了
> 
> 太棒了，效率真高，高手！！！，ps：那个“检查API额度”的报错也需要修改一下
> 
> 感谢你的回复！！！

这个估计是因为你cf worker没转换这几个请求，报404
v1/dashboard/billing/subscription
v1/dashboard/billing/usage
你看下微软的有没有类似接口也转一下

**Comment by CattleZoe** [comment]
> > > > 是的
> > > 
> > > 
> > > 好了，你用最新版试试，忘了容错了
> > 
> > 
> > 太棒了，效率真高，高手！！！，ps：那个“检查API额度”的报错也需要修改一下
> > 感谢你的回复！！！
> 
> 这个估计是因为你cf worker没转换这几个请求，报404 v1/dashboard/billing/subscription v1/dashboard/billing/usage 你看下微软的有没有类似接口也转一下

好的，了解了！感谢，可以close了
