### ISSUE TITLE
移动端点击出现蓝色遮罩，闪眼睛影响使用

### ISSUE THREAD

**Issue by UerLink** [xqdoo00o/chatgpt-web#56]
### 修改代码：
```css
-webkit-tap-highlight-color:rgba(0,0,0,0);
```
经过测试添加上述代码到css 文件中 *{ }，就不显示了。
```css
*{

}
````

### 问题复现
![bug](https://github.com/xqdoo00o/chatgpt-web/assets/73655157/e6f3f2eb-d8d7-4ed6-aadf-f206af45e7cc)

**Comment by xqdoo00o** [comment]
已修复
