### ISSUE TITLE
大佬你好我想在必应语音上创建自己的列表来调用方便调整顺序怎么弄呀

### ISSUE THREAD

**Issue by yuantouw** [xqdoo00o/chatgpt-web#57]
想自己在必应语音上创建表来代替默认的
研究了很久不知道怎么弄，不知道是不是这里

<img width="1379" alt="image" src="https://github.com/xqdoo00o/chatgpt-web/assets/73607554/6164dd74-ebe8-4fe9-a6c0-996dcd7bbeb9">

**Comment by xqdoo00o** [comment]
不懂了，我也是借别人的测的。之后会优化下列表显示顺序，大陆的放前面

**Comment by yuantouw** [comment]
> 不懂了，我也是借别人的测的。之后会优化下列表显示顺序，大陆的放前面

好的谢谢

**Comment by xqdoo00o** [comment]
好了
