### ISSUE TITLE
作者，能否适配最新的GPT联网功能，目前3.5和4.0均可以联网获得答案了

### ISSUE THREAD

**Issue by gsfilm** [xqdoo00o/chatgpt-web#58]

**Comment by xqdoo00o** [comment]
目前用api的话，暂时没办法联网，你可以试试把网页版模拟成api，[ChatGPT-to-API](https://github.com/xqdoo00o/ChatGPT-to-API)，网页设置里改OpenAI接口到模拟的api地址 http://127.0.0.1:8080/  。然后再试试能不能联网，我没plus会员暂时测不了gpt-4

**Comment by gsfilm** [comment]
该项目的详细部署教程，有中文版吗？我有GPT-4，不妨测试测试。
还有就是这个模拟API的说明作者方便提供吗？

**Comment by xqdoo00o** [comment]
刚更新了[文档](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md)
注意无法直连chat.openai.com的话，增加个代理文件proxies.txt

**Comment by eureka6** [comment]
> 当前使用api的话，暂时没有办公法联网，你可以试试把网页版模拟成api，用这个项目[ChatGPT-to-API](https://github.com/xqdoo00o/ChatGPT-to-API)，网页设置里改OpenAI接口到模拟的api地址[http://127.0.0.1:8080 /](http://127.0.0.1:8080/) 。然后再试试不能联网，我没有加会员暂测没有gpt-4

大佬，我想问一下，这个API是怎么处理对话历史的？是一个用户创建一个独立对话，还是轮询对话列表？

**Comment by xqdoo00o** [comment]
> > 当前使用api的话，暂时没有办公法联网，你可以试试把网页版模拟成api，用这个项目[ChatGPT-to-API](https://github.com/xqdoo00o/ChatGPT-to-API)，网页设置里改OpenAI接口到模拟的api地址[http://127.0.0.1:8080 /](http://127.0.0.1:8080/) 。然后再试试不能联网，我没有加会员暂测没有gpt-4
> 
> 大佬，我想问一下，这个API是怎么处理对话历史的？是一个用户创建一个独立对话，还是轮询对话列表？

目前每条提问创建一个单独会话，多个用户的话，就是轮询创建

**Comment by eureka6** [comment]
> > > 当前使用api的话，暂时没有办公法联网，你可以试试把网页版模拟成api，用这个项目[ChatGPT-to-API](https://github.com/xqdoo00o/ChatGPT-to-API)，网页设置里改OpenAI接口到模拟的api地址[http://127.0.0.1:8080 /](http://127.0.0.1:8080/) 。然后再试试不能联网，我没有加会员暂测没有gpt-4
> > 
> > 
> > 大佬，我想问一下，这个API是怎么处理对话历史的？是一个用户创建一个独立对话，还是轮询对话列表？
> 
> 目前每条提问创建一个单独会话，多个用户的话，就是轮询创建

好的，谢谢

**Comment by gsfilm** [comment]
感觉修改了这个设置的布局反而显得麻烦了，还是之前版本的布局比较舒服，还有，作者是否能实现OpenAi接口那里做成下拉选项，同时添加自定义选项，选择自定义就在下方多出一个输入框进行自定义接口的功能。

**Comment by xqdoo00o** [comment]
> 感觉修改了这个设置的布局反而显得麻烦了，还是之前版本的布局比较舒服，还有，作者是否能实现OpenAi接口那里做成下拉选项，同时添加自定义选项，选择自定义就在下方多出一个输入框进行自定义接口的功能。

什么意思，能给个UI示例吗

**Comment by gsfilm** [comment]
https://ai.igmsy.xyz
无法发图片，可以上去看一看，设置OpenAI的接口那种下拉选项
https://ai.igmsy.xyz/Keys.html
这个Key查询所使用到的就是添加一个自定义的选项

**Comment by xqdoo00o** [comment]
> 感觉修改了这个设置的布局反而显得麻烦了，还是之前版本的布局比较舒服，还有，作者是否能实现OpenAi接口那里做成下拉选项，同时添加自定义选项，选择自定义就在下方多出一个输入框进行自定义接口的功能。

好了

**Comment by gsfilm** [comment]
下拉选项API接口能实现吗？
