### ISSUE TITLE
请教ChatGPT-to-API 如何生成 accessToken?

### ISSUE THREAD

**Issue by tanpengsccd** [xqdoo00o/chatgpt-web#61]
https://github.com/xqdoo00o/ChatGPT-to-API  这个项目 没开 issue,只能在这里问了.
我感觉有时候 能自己 生成  acessToken.json,但是更多时候 一直都是 "[]" 空的.

**Comment by xqdoo00o** [comment]
> https://github.com/xqdoo00o/ChatGPT-to-API 这个项目 没开 issue,只能在这里问了. 我感觉有时候 能自己 生成 acessToken.json,但是更多时候 一直都是 "[]" 空的.

配置下accounts.txt，然后直接运行程序就生成了

**Comment by tanpengsccd** [comment]
我配置了.

**Comment by xqdoo00o** [comment]
> 我配置了.

运行程序时提示你 updating access token for 你的邮箱吗

**Comment by xqdoo00o** [comment]
> 

代码是最新的吗

**Comment by xqdoo00o** [comment]
> 是的. 昨晚看你发布了更新就更新了. 我手动填入 accessToken 是完全可用的.

你搜下代码里有没有"Updating access token for"，这个是最新代码，或者删掉程序，重新编译下

**Comment by tanpengsccd** [comment]
> > 是的. 昨晚看你发布了更新就更新了. 我手动填入 accessToken 是完全可用的.
> 
> 你搜下代码里有没有"Updating access token for"，这个是最新代码，或者删掉程序，重新编译下

晚上 开了下 debug 断点 发现是 accounts.txt 写成 account.txt 了.
