### ISSUE TITLE
5月24更新的最新版本移动端提示访问接口失败，电脑端正常

### ISSUE THREAD

**Issue by yuantouw** [xqdoo00o/chatgpt-web#62]
5月24更新的最新版本移动端提示访问接口失败，电脑端正常

**Comment by xqdoo00o** [comment]
移动端使用什么浏览器，什么系统呢

**Comment by yuantouw** [comment]
> 移动端使用什么浏览器，什么系统呢

安卓，苹果，以及谷歌浏览器里f12改成移动端发送信息都不行，但是火狐浏览器f12改成移动端可以，可能反代有问题了

**Comment by yuantouw** [comment]
> 移动端使用什么浏览器，什么系统呢

切换到之前的版本移动端均正常，用了你的demo测试了下也是移动端不行

**Comment by yuantouw** [comment]
<img width="1647" alt="image" src="https://github.com/xqdoo00o/chatgpt-web/assets/73607554/b2dba6fc-09cd-4355-8e38-74d3af92a532">

**Comment by xqdoo00o** [comment]
移动端也是报这个错吗
没复现额

**Comment by xqdoo00o** [comment]
> > 移动端也是报这个错吗 没复现额
> 
> 用电脑模拟移动端提示访问接口失败，移动真机发送后发送按钮会一直提示处理状态，最后提示超时

电脑端你把上面我发的offline那里改掉。移动端的话，你的接口能正常使用吗

**Comment by yuantouw** [comment]
> offline

电脑端改掉offline恢复正常，移动端我没用自定义接口，用的

server {
    listen       80;
    server_name  example.com;
    #开启openai接口的gzip压缩，大量重复文本的压缩率高，节省服务端流量
    gzip  on;
    gzip_min_length 1k;
    gzip_types text/event-stream;

    #如需部署在网站子路径，如"example.com/chatgpt"，配置如下
    #location ^~ /chatgpt/v1 {
    location ^~ /v1 {
        proxy_pass https://api.openai.com/v1;
        proxy_set_header Host api.openai.com;
        proxy_ssl_name api.openai.com;
        proxy_ssl_server_name on;
        proxy_set_header Authorization $gptauth;
        proxy_pass_header Authorization;
        #流式传输，不关闭buffering缓存会卡死，必须配置！！！
        proxy_buffering off;
        
        这个反代，但是移动端。我用老版本的代码是正常，的用新版本（昨天更新的）就会这样，超时

**Comment by xqdoo00o** [comment]
> > offline
> 
> 电脑端改掉offline恢复正常，移动端我没用自定义接口，用的
> 
> server { listen 80; server_name example.com; #开启openai接口的gzip压缩，大量重复文本的压缩率高，节省服务端流量 gzip on; gzip_min_length 1k; gzip_types text/event-stream;
> 
> ```
> #如需部署在网站子路径，如"example.com/chatgpt"，配置如下
> #location ^~ /chatgpt/v1 {
> location ^~ /v1 {
>     proxy_pass https://api.openai.com/v1;
>     proxy_set_header Host api.openai.com;
>     proxy_ssl_name api.openai.com;
>     proxy_ssl_server_name on;
>     proxy_set_header Authorization $gptauth;
>     proxy_pass_header Authorization;
>     #流式传输，不关闭buffering缓存会卡死，必须配置！！！
>     proxy_buffering off;
>     
>     这个反代，但是移动端。我用老版本的代码是正常，的用新版本（昨天更新的）就会这样，超时
> ```

你移动端和电脑是同一个网络吗，你说的新版本是nginx的新配置吗，还是新版本的HTML。

**Comment by yuantouw** [comment]
> 

电脑用线连的，移动连的wifi但都是一个路由器出来。

新版和旧版都是

#如需部署在网站子路径，如"example.com/chatgpt"，配置如下
#location ^~ /chatgpt/v1 {
location ^~ /v1 {
    proxy_pass https://api.openai.com/v1;
    proxy_set_header Host api.openai.com;
    proxy_ssl_name api.openai.com;
    proxy_ssl_server_name on;
    proxy_set_header Authorization $gptauth;
    proxy_pass_header Authorization;
    #流式传输，不关闭buffering缓存会卡死，必须配置！！！
    proxy_buffering off;
    
    这个反代，但是移动端。我用老版本的代码是正常，的用新版本（昨
    #如需部署在网站子路径，如"example.com/chatgpt"，配置如下
#location ^~ /chatgpt/v1 {
location ^~ /v1 {
    proxy_pass https://api.openai.com/v1;
    proxy_set_header Host api.openai.com;
    proxy_ssl_name api.openai.com;
    proxy_ssl_server_name on;
    proxy_set_header Authorization $gptauth;
    proxy_pass_header Authorization;
    #流式传输，不关闭buffering缓存会卡死，必须配置！！！
    proxy_buffering off;
    
    
    之前的配置没动过，
    
    旧版可以使用，新版就会有超时提示，

**Comment by xqdoo00o** [comment]
> 

就是说你的nginx配置没变，只是更新了HTML是吧？

**Comment by yuantouw** [comment]
> > 
> 
> 就是说你的nginx配置没变，只是更新了HTML是吧？

对的，每次更新我都只更新了html呀，nginx配置不动，而且我没启用sw.js

**Comment by xqdoo00o** [comment]
> > > 
> > 
> > 
> > 就是说你的nginx配置没变，只是更新了HTML是吧？
> 
> 对的，每次更新我都只更新了html呀，nginx配置不动，而且我没启用sw.js

那你清一下移动端浏览器的缓存，再试试。

**Comment by yuantouw** [comment]
> > > > 
> > > 
> > > 
> > > 就是说你的nginx配置没变，只是更新了HTML是吧？
> > 
> > 
> > 对的，每次更新我都只更新了html呀，nginx配置不动，而且我没启用sw.js
> 
> 那你清一下移动端浏览器的缓存，再试试。

我重新下载了新的浏览器也不行还是超时

**Comment by yuantouw** [comment]
我换个域名重新全新安装试下排除本地缓存的问题试试

**Comment by xqdoo00o** [comment]
> 

可能域名被移动拦截了吧，上个HTTPS好些

**Comment by yuantouw** [comment]
> > 
> 
> 可能域名被移动拦截了吧，上个HTTPS好些

就是用的https，问题在于，老站点旧版index.htm正常，我只是把index.html换成新版的，就不行了。百思不得其解呜呜呜呜

**Comment by yuantouw** [comment]
https://github.com/xqdoo00o/chatgpt-web/assets/73607554/da77601f-7de2-435d-9af8-380df23a1fec

没工具查看手机端的调试，我发现了就是缓存问题，这个浏览器用过之前的旧版，让后更新了新版后就会存在之前的说的问题。

缓存咋的都清不掉，浏览器自带清理功能的都清不掉，部分功能代码被缓存了，所以有问题唉

**Comment by xqdoo00o** [comment]
那你可以加下pwa，每次更新sw.js里面的版本号就更新了

**Comment by yuantouw** [comment]
> 那你可以加下pwa，每次更新sw.js里面的版本号就更新了

试过了加了pwa这个浏览器之前的缓存还是在，

手机的谷歌浏览器可以完全清除掉缓存，其他浏览器基本不可以。其他手机浏览器的老用户基本出现超时，不回复的情况，呜呜呜呜

**Comment by xqdoo00o** [comment]
更新了，加了个强制刷新按钮
