### ISSUE TITLE
移动设备使用出错

### ISSUE THREAD

**Issue by yuyanlike** [xqdoo00o/chatgpt-web#66]
出现一个问题 是手机上在输入框输入的apikey好像有问题 使用一直报错，在pc上输入同一个密钥没有问题。包括在pc上使用开发者工具模拟手机设备使用也没有问题。

**Comment by xqdoo00o** [comment]
> 出现一个问题 是手机上在输入框输入的apikey好像有问题 使用一直报错，在pc上输入同一个密钥没有问题。包括在pc上使用开发者工具模拟手机设备使用也没有问题。

没复现呢，可以debug手机端看下么，输入的是否正确

**Comment by eureka6** [comment]
手机端的浏览器好像有缓存的问题，更新html文件后，要强制刷新或者清除缓存才会显示最新的。
这是不是应该在nginx里加个缓存过期？

**Comment by xqdoo00o** [comment]
我加个强制刷新按钮好了

**Comment by eureka6** [comment]
> 我加个强制刷新按钮好了

大佬，还有一个问题，就是“api模式”和“chatgpt to api模式”有什么简单丝滑的切换方式吗？比如说前端放两个按钮，或者多弄几个代理地址？

**Comment by suzhouhu** [comment]
触摸屏上无法输入，比如教室里的触摸屏，无法完成激活输入文本框，然而用鼠标点击却能激活输入文本框！

**Comment by xqdoo00o** [comment]
> 触摸屏上无法输入，比如教室里的触摸屏，无法完成激活输入文本框，然而用鼠标点击却能激活输入文本框！

其他网页有这种情况吗。还是只有这个不行

**Comment by suzhouhu** [comment]
其他网页能够输入的！就这个文本框仿佛禁用了，敲了半天都无法输入

**Comment by xqdoo00o** [comment]
> 其他网页能够输入的！就这个文本框仿佛禁用了，敲了半天都无法输入

是光标无法定位到文本输入框是吧

**Comment by mass0806** [comment]
更新后的确存在浏览器兼容问题，小米手机自带浏览器出现以下功能异常：1.主界面清空会话失败。2.主界面点击喇叭不能播放语音，但是能下载语音。同时不能自动朗读。3.左边菜单删除会话失败，删除全部会话失败，新建会话失败。而使用谷歌浏览器(win10或手机)就无问题

**Comment by xqdoo00o** [comment]
> 更新后的确存在浏览器兼容问题，小米手机自带浏览器出现以下功能异常：1.主界面清空会话失败。2.主界面点击喇叭不能播放语音，但是能下载语音。同时不能自动朗读。3.左边菜单删除会话失败，删除全部会话失败，新建会话失败。而使用谷歌浏览器(win10或手机)就无问题

已修复，并添加强制刷新网页按钮

**Comment by xqdoo00o** [comment]
> > 我加个强制刷新按钮好了
> 
> 大佬，还有一个问题，就是“api模式”和“chatgpt to api模式”有什么简单丝滑的切换方式吗？比如说前端放两个按钮，或者多弄几个代理地址？

加好了

**Comment by eureka6** [comment]
> > > 我加个强制刷新按钮好了
> > 
> > 
> > 大佬，还有一个问题，就是“api模式”和“chatgpt to api模式”有什么简单丝滑的切换方式吗？比如说前端放两个按钮，或者多弄几个代理地址？
> 
> 加好了

大佬牛逼
