### ISSUE TITLE
“chatgpt-to-api”和“nginx反代api”如何共存？

### ISSUE THREAD

**Issue by eureka6** [xqdoo00o/chatgpt-web#68]
前端只能请求一个api地址

而`chatgpt-to-api`的使用地址是`/v1/xxx`
`nginx反代api`的使用地址也是`/v1/xxx`

这样应该会冲突吧？

那怎样在一个前端上同时使用两种api呢？

**Comment by eureka6** [comment]
- 如果只用官方的api的话，GPT模型里的`gpt-4-联网`是不是就不能用了？或者实际请求的是`gpt3.5`？

- 我用`chatgpt-to-api`的时候，`gpt-3.5`和`gpt-4-联网`都能用，是不是部署成功了？访问`gpt-3.5`是不是就是在访问`chatgpt-to-api`？

- `chatgpt-to-api`的环境变量在哪里配置呢？我按照代码部署了，也成功访问过了，结果第二天报错`无法访问接口`，是不是没设置`环境变量`的问题呀？

**Comment by xqdoo00o** [comment]
> * 如果只用官方的api的话，GPT模型里的`gpt-4-联网`是不是就不能用了？或者实际请求的是`gpt3.5`？
> * 我用`chatgpt-to-api`的时候，`gpt-3.5`和`gpt-4-联网`都能用，是不是部署成功了？访问`gpt-3.5`是不是就是在访问`chatgpt-to-api`？
> * `chatgpt-to-api`的环境变量在哪里配置呢？我按照代码部署了，也成功访问过了，结果第二天报错`无法访问接口`，是不是没设置`环境变量`的问题呀？

1，对，除非你有gpt-4的api权限
2，非plus账户的话，其实都是3.5，只是选择用4也不报错
3，这个是go前台程序，断开ssh就停止运行了。要一直运行的话，需要后台运行。
linux的话，`./freechatgpt >/dev/null 2>&1 &` 就可以放后台运行了

**Comment by eureka6** [comment]
那大佬，你的那个很好用的项目：`openai-proxy`，里面有条`Orgin`，作用是限定前端的域名对吗？如果别人通过改本地`host`的方式，会不会绕过去这个限制呀？

**Comment by xqdoo00o** [comment]
> 那大佬，你的那个很好用的项目：`openai-proxy`，里面有条`orgin`，作用是限定前端的域名对吗？如果别人通过改本地`host`的方式，会不会绕过去这个限制呀？

那确实也可以，只要别人能猜到你那个允许的域名列表里的
