### ISSUE TITLE
关于增加自动发送按钮 和关键字发送 和唤醒词设置

### ISSUE THREAD

**Issue by joe12801** [xqdoo00o/chatgpt-web#70]
关于增加自动发送按钮 和关键字发送 和唤醒词设置
<img width="525" alt="758c0c7a86577b1e5dbae4d1c962d7b" src="https://github.com/xqdoo00o/chatgpt-web/assets/70465495/6fc60894-3184-4c67-a02e-8ad6ef915916">

唤醒词 可以picovoice.ai
文档参考
https://picovoice.ai/docs/quick-start/porcupine-web/

**Comment by joe12801** [comment]
![image](https://github.com/xqdoo00o/chatgpt-web/assets/70465495/b765a0bb-924d-4e47-986d-a6caf9940f1f)
应该还要加一个停上MIC的关键词

**Comment by xqdoo00o** [comment]
好了
