### ISSUE TITLE
说完话，自动发送消息的功能

### ISSUE THREAD

**Issue by joe12801** [xqdoo00o/chatgpt-web#71]
除了关键字发送消息，还加另一个方式  可供选择。那就是说完了之后。在1-2s 没有收到消息，就自动会发送消息给chatgpt.加一个按钮。，说完之后，再继续监听mic, 想停止，用停止关键词

![image](https://github.com/xqdoo00o/chatgpt-web/assets/70465495/258cd011-3811-4a64-b4e2-f52abb19afdb)

**Comment by xqdoo00o** [comment]
已添加

**Comment by joe12801** [comment]
> 已添加

厉害大佬
