### ISSUE TITLE
建议增加基于mask的简单密码功能

### ISSUE THREAD

**Issue by Gipors** [xqdoo00o/chatgpt-web#73]
咱们主打的就是一个纯html部署，确实是非常优秀，虽然不能记录chat的内容。
既然已经能配置 nginx了，多套一层 php 或者别的语言也不是不可以，但确实有违 纯html 的初衷。
有看到网友提的 issue，设置 basic_auth 导致 api key 报错不可用，我也试了，确实不可用。

想来最好的方式是，希望能设置一个基于 mask 的简单密码功能，就在开屏的 loadMask 上稍作修改即可。
虽然这种锁页面的方式很弱，但我想绝大部分的用户是不会知道如何查看源码来破解的，或者在html做个 md5 的验证也不是不可以。就如古时的柴扉，来人也懂得需要“小扣柴扉”。

希望大佬能考虑增加此功能，这版产品的UI是我最喜欢的，希望越做越好！

![image](https://github.com/xqdoo00o/chatgpt-web/assets/127558/897ad0be-637b-449a-bc6c-b8e0e2f96098)

**Comment by xqdoo00o** [comment]
好了，请参考文档

**Comment by Gipors** [comment]
> 好了，请参考文档
大佬神速！

感谢大佬响应增加新功能，已用上密码功能，使用一切正常，体验很好！
再次感谢！

**Comment by xqdoo00o** [comment]
> 咱们主打的就是一个纯html部署，确实是非常优秀，虽然不能记录chat的内容。

这里的记录是啥意思，可以记录内容的。

**Comment by Gipors** [comment]
还发现一个语言合成的问题，不知道是否可以解决。

中文角色朗读英文时感觉全是 Chinglish，而英文角色似乎又不能朗读中文。

能否分开设置中文和英文的语音角色，以应对这种体验不佳的情况？

我现在是手动切换需要的角色以适应英文或中文内容，但似乎切换角色后需要刷新一下网页才能生效，稍微有些麻烦了。

**Comment by Gipors** [comment]
> > 咱们主打的就是一个纯html部署，确实是非常优秀，虽然不能记录chat的内容。
> 
> 这里的记录是啥意思，可以记录内容的。

就是记录对话的内容，存档以便之后可再回溯查看。

**Comment by xqdoo00o** [comment]
> > > 咱们主打的就是一个纯html部署，确实是非常优秀，虽然不能记录chat的内容。
> > 
> > 
> > 这里的记录是啥意思，可以记录内容的。
> 
> 就是记录对话的内容，数据库或本文形式，存档以便之后可再回溯查看。

你可以在设置-数据-会话里导出json格式的数据，清空内容后可以再导入

**Comment by xqdoo00o** [comment]
> 还发现一个语言合成的问题，不知道是否可以解决。
> 
> 中文角色朗读英文时感觉全是 Chinglish，而英文角色似乎又不能朗读中文。
> 
> 能否分开设置中文和英文的语音角色，以应对这种体验不佳的情况？
> 
> 我现在是手动切换需要的角色以适应英文或中文内容，但似乎切换角色后需要刷新一下网页才能生效，稍微有些麻烦了。

不能，这个要拆分内容很麻烦，而且不需要刷新网页生效，等上次读完，重新点播放就好了

**Comment by Gipors** [comment]
> > > > 咱们主打的就是一个纯html部署，确实是非常优秀，虽然不能记录chat的内容。
> > > 
> > > 
> > > 这里的记录是啥意思，可以记录内容的。
> > 
> > 
> > 就是记录对话的内容，数据库或本文形式，存档以便之后可再回溯查看。
> 
> 你可以在设置-数据-会话里导出json格式的数据，清空内容后可以再导入

感谢，没有留意到这个功能。。。

**Comment by Gipors** [comment]
> > 还发现一个语言合成的问题，不知道是否可以解决。
> > 中文角色朗读英文时感觉全是 Chinglish，而英文角色似乎又不能朗读中文。
> > 能否分开设置中文和英文的语音角色，以应对这种体验不佳的情况？
> > 我现在是手动切换需要的角色以适应英文或中文内容，但似乎切换角色后需要刷新一下网页才能生效，稍微有些麻烦了。
> 
> 不能，这个要拆分内容很麻烦，而且不需要刷新网页生效，等上次读完，重新点播放就好了

好的，那我再多试试。谢谢~
