### ISSUE TITLE
Translation Question

### ISSUE THREAD

**Issue by oleteacher** [xqdoo00o/chatgpt-web#74]
First, the project just keeps getting better and better - thank you.

Using in a classroom environment. Running into some translation issues. Is there a way to translate the file (index.html) here on GitHub? Cannot find an easy way to translate html doc, so looking for guidance.

Thank you

**Comment by xqdoo00o** [comment]
Added. If want English as default lang, change [here](https://github.com/xqdoo00o/chatgpt-web/blob/main/index.html#L2886) `zh` to `en`. Also if you want to polish the [English translations](https://github.com/xqdoo00o/chatgpt-web/blob/main/index.html#L2896), welcome PR!

**Comment by oleteacher** [comment]
Thank you David, that is helpful.

Hopefully this will make it easier to get approval for updates on the school server. The process to get approvals is not so easy. We (as in a teacher) submit the updated files, then each is reviewed before they can go live. If the HTML/JS/PHP is in any other lang beside english, it is rejected. So I have to go through each update and manually change langs to english.

Thank you again.
