### ISSUE TITLE
关于增加唤醒的功能

### ISSUE THREAD

**Issue by joe12801** [xqdoo00o/chatgpt-web#76]
![image](https://github.com/xqdoo00o/chatgpt-web/assets/70465495/cc60ab53-4b26-46aa-8f63-f24ec27e9884)

在保持监听的情况下，可以增加唤醒词。像 苹果手机 hey siri  小米手机，小爱同学。，然后就可以连续 对话了
比如在10内，没有应答。就退出语音识别。后台继续保存保挂监听MIC。方便下次唤醒。
关键唤醒有很成熟的AI   PicoVoice离线语音AI引擎 每个月可以免费训练三个唤醒词
![image](https://github.com/xqdoo00o/chatgpt-web/assets/70465495/adf747ed-0306-4e1e-b0bb-916ace66cbb9)

开发文档 https://picovoice.ai/docs/quick-start/porcupine-web/
看看有没有可能折腾下

**Comment by xqdoo00o** [comment]
这个不行，跟现有逻辑冲突，点击按钮是直接识别还是等待唤醒词。说唤醒词开始识别也太麻烦。按现有逻辑 点击或快捷键 直接唤醒比较好，而且一直保持监听也不太好。
