### ISSUE TITLE
大佬好，项目存放在二级目录出现头像调用错误

### ISSUE THREAD

**Issue by yuantouw** [xqdoo00o/chatgpt-web#77]
项目存放在其他站点的二级目录，就会出现头像调用错误，还有左侧会自动搜索

<img width="603" alt="image" src="https://github.com/xqdoo00o/chatgpt-web/assets/73607554/97d5b26e-83ba-4391-94fa-db2c2ad47da8">

就是主站有账号登陆功能，主站保存了登陆账户和密码在浏览器，导致二级目录的本gpt项目头像会调用错误。错误的把头像地址调成了被保存的用户名》

搜索功能则直接默认搜索了被保存的用户名，

除了谷歌浏览器外，大部分浏览器都有这样的情况。

请问该怎么解决呀

**Comment by xqdoo00o** [comment]
这个头像的url是多少，右键检查看下，是只有chrome才正常吗

**Comment by yuantouw** [comment]
> 这个头像的url是多少，右键检查看下，是只有chrome才正常吗


错误头像：https://域名/admin（主站保存的用户名）

自动搜索：admin（主站保存的用户名）

**Comment by xqdoo00o** [comment]
这个头像地址要是个图片地址的，这个头像admin网址是图片吗？
自动搜索 admin是什么意思，能上个图吗

**Comment by yuantouw** [comment]
<img width="643" alt="image" src="https://github.com/xqdoo00o/chatgpt-web/assets/73607554/afbf34b0-d2dc-4f31-b395-af6635f4ead5">
意思是这个是我主站后台，https://www.域名.com/houtai/

如图，我的登陆账户保存在浏览器，用的时候会自动填充，

gpt项目头像就会调用了我保存到浏览器的用户名。

src="https://域名/admin"

头像变成了这样，

**Comment by yuantouw** [comment]
<img width="1333" alt="image" src="https://github.com/xqdoo00o/chatgpt-web/assets/73607554/0f64bbf1-e760-430d-91b7-1294dafc000a">

**Comment by yuantouw** [comment]
<img width="1504" alt="image" src="https://github.com/xqdoo00o/chatgpt-web/assets/73607554/67330bc1-8c70-4cfb-ba5f-9a9fd8e20f62">

**Comment by yuantouw** [comment]
<img width="1596" alt="image" src="https://github.com/xqdoo00o/chatgpt-web/assets/73607554/9f6c779a-1624-4b35-ad33-b0f4d8722c6d">

**Comment by xqdoo00o** [comment]
已尝试修复，更新下试试

**Comment by yuantouw** [comment]
谷歌浏览器正常，火狐浏览器百分之百调用保存的账户信息，必应浏览器，有时正常有时不正常，


手机端大部分浏览器也是头像调用错误，

**Comment by yuantouw** [comment]
好的，谢谢。

**Comment by xqdoo00o** [comment]
没错误了吧

**Comment by yuantouw** [comment]
> 没错误了吧

没有错误了，谢谢你！
