### ISSUE TITLE
老大好，页面字数限制了，写一篇文章就不够了，只能删除前文或者新开，有什么好的解决办法吗

### ISSUE THREAD

**Issue by KuXian-hub** [xqdoo00o/chatgpt-web#78]
老大好，页面字数限制了，写一篇文章就不够了，只能删除前文或者新开，有什么好的解决办法吗

**Comment by xqdoo00o** [comment]
可以试下打开长回复。具体作用可以看文档

**Comment by KuXian-hub** [comment]
显示的这个："请求内容过大，请删除部分对话或打开设置关闭连续对话！"

**Comment by xqdoo00o** [comment]
那就没办法了，4k的token限制，不过你可以试试快用完4k字数的时候，发下 “总结上文”，把前面写的简短总结下，在总结的基础上，继续问

**Comment by KuXian-hub** [comment]
好的，谢谢大佬
