### ISSUE TITLE
如果当前主题是dark，在刷新页面的时候会闪屏

### ISSUE THREAD

**Issue by luy98** [xqdoo00o/chatgpt-web#79]
本质原因是会先加载出lighting模式的加载页，所以就会看起来"闪"一下。
我研究了下代码，是因为加载页遮罩出来的时候，设置主题的代码还没有被执行到。
我目前的临时方案是将设置主题的代码放在head里面单独作为一个js执行，这样就能确保先加载出主题再渲染页面了。
还有更好的方案吗？

**Comment by xqdoo00o** [comment]
确实，修复了
