### ISSUE TITLE
有时无法正确自动滚动，下面有一部分看不到

### ISSUE THREAD

**Issue by 6uu1** [xqdoo00o/chatgpt-web#8]
提个建议，最好是下面离输入框始终保持一小段空白，这样子滚动的时候更加美观！

**Comment by xqdoo00o** [comment]
代码是最新的吗

**Comment by xqdoo00o** [comment]
无法自动滚动是因为离底部太远，所以就不自动滚动了

**Comment by xqdoo00o** [comment]
> > 代码是最新的吗
> 
> 是的

看起来不是最新的，你更新到今天的版本试试
然后用的浏览器是哪个版本的也发下
