### ISSUE TITLE
你太棒了

### ISSUE THREAD

**Issue by tomatocuke** [xqdoo00o/chatgpt-web#81]
赞美你，真的很不错！ 尤其是语音合成和角色扮演，太酷了。

## 我稍微做了点修改
1. 主要是上下文。想给朋友用，但是他们又不懂花费，还是我买单，开上下文太费钱了。所以我隐藏了【连续会话】的切换按钮，默认关闭。必须新会话加关键词来开启，定时关闭，或者切换会话关闭
2. 发现本地好多引用的js和css不能打开。地址为啥是 href="//xxx.js" ? 我加上了https，让本地能直接file:// 打开页面。

## 遇到的小问题
1. 微信打开网页，可以显示语音输入小标，但是不可用。
2. 控制台小报错。暂时没发现影响了什么。`TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported  at sw.js?1686221539443:19:19`

## 疑问
1. 我看到有说token计数的那个，你有尝试吗？考虑更新这个吗？
2. 语音合成的是完全免费的吗？
3. 能否对会话加上【角色扮演】和【连续会话】的控制？ 这样我可以一个会话翻译（给角色但不连续）、一个会话聊天（连续无所谓角色）
4. 想加自己的api接口调用。你的代码很整洁，但是很多，我还是不太清晰整个流程。看到了api调用那里，也不太清楚我应该怎么去做一些嵌入。   （主要想加身份验证之类的，我现在是给朋友免费用，但是也想简单的控制每个人的使用量，别给我干太多 😭，如果比较OK，再做付费的给不认识的人）

非常感谢，我想加你QQ方便交流，或者你加我QQ：772532526

**Comment by xqdoo00o** [comment]
1，技术没太大难度，只是没考虑好。
2，如果选edge和系统是免费的。
3，可以考虑。
4，要付费肯定要后端的，这只是纯前端项目

暂时不考虑单独交流
