### ISSUE TITLE
手机上即使给了麦克风权限依然提示没给权限

### ISSUE THREAD

**Issue by lin-1259** [xqdoo00o/chatgpt-web#86]
大佬你好，如标题所说，是手机的问题还是部署的问题，我是直接把代码下载后用宝塔新建网站，然后把文件放进去的，需要PHP环境吗，我选的的是php8.2

**Comment by xqdoo00o** [comment]
是https吗，用手机chrome试试

**Comment by lin-1259** [comment]
嗯嗯, 是https,可能是因为我手机的原因,电脑上,别的手机都可以使用语音
