### ISSUE TITLE
Question: Custom Endpoint on the HTML file

### ISSUE THREAD

**Issue by mxrk314** [xqdoo00o/chatgpt-web#88]
Hi, I want to directly add my custom endpoint to the index.html itself, can you help me which line should i add or change the value? 

anyway, thanks for this, youre awesome!

**Comment by xqdoo00o** [comment]
Line 2677

**Comment by mxrk314** [comment]
thanks for the quick reply, how about for the api key? sorry if im too noob with these..

**Comment by xqdoo00o** [comment]
Linne 2685

**Comment by yojner** [comment]
thank you so much bro.. :)

**Comment by mxrk314** [comment]
> Linne 2685

thanks sir, will close now..
