### ISSUE TITLE
总是出来半句对话

### ISSUE THREAD

**Issue by suzhouhu** [xqdoo00o/chatgpt-web#9]
![IMG_3149](https://user-images.githubusercontent.com/23079693/226096906-6241ccf0-d1e5-45e5-9c38-4523589a0350.PNG)

**Comment by xqdoo00o** [comment]
是不是手机网页被缩放了

**Comment by chatechat** [comment]
通用情况 问 背诵一首鹅鹅鹅 回答：鹅鹅鹅，曲项向天歌。 白毛浮绿水

**Comment by chatechat** [comment]
> 通用情况 问 背诵一首鹅鹅鹅 回答：鹅鹅鹅，曲项向天歌。 白毛浮绿水

只有本地打开才有这种情况，线上部署没问题。

**Comment by suzhouhu** [comment]
&nbsp;


刘鹄中
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wiesław ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 下午3:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xqdoo00o/chatgpt-web] 总是出来半句对话 (Issue #9)





   
通用情况 问 背诵一首鹅鹅鹅 回答：鹅鹅鹅，曲项向天歌。 白毛浮绿水
  
只有本地打开才有这种情况，线上部署没问题。
  
终于知道了
 fetch("https://cdn.jsdelivr.net/gh/PlexPt/awesome-chatgpt-prompts-zh/prompts-zh.json" 这个文件访问不了就是说话说一半

**Comment by xqdoo00o** [comment]
> > > 通用情况 问 背诵一首鹅鹅鹅 回答：鹅鹅鹅，曲项向天歌。 白毛浮绿水
> > 
> > 
> > 只有本地打开才有这种情况，线上部署没问题。
> 
> 终于知道了 fetch("https://cdn.jsdelivr.net/gh/PlexPt/awesome-chatgpt-prompts-zh/prompts-zh.json" 这个文件访问不了就是说话说一半

无法复现额，就算我把这个请求删了也正常额

**Comment by gmugu** [comment]
![1680680271712](https://user-images.githubusercontent.com/8317478/230001006-260c5b46-2616-4083-9c0f-86dedbffa943.jpg)
![1680680320725](https://user-images.githubusercontent.com/8317478/230001029-a28fa882-473f-4c6d-bd21-fde89864142a.jpg)
我复现了这个问题，并且在代码中加了打印，问题应该出在readChunk()函数，并不是每一次回调的数据都是 "data: {...}\n\n"这样完整的格式

**Comment by xqdoo00o** [comment]
> ![1680680271712](https://user-images.githubusercontent.com/8317478/230001006-260c5b46-2616-4083-9c0f-86dedbffa943.jpg) ![1680680320725](https://user-images.githubusercontent.com/8317478/230001029-a28fa882-473f-4c6d-bd21-fde89864142a.jpg) 我复现了这个问题，并且在代码中加了打印，问题应该出在readChunk()函数，并不是每一次回调的数据都是 "data: {...}\n\n"这样完整的格式

使用nginx反代接口了吗

**Comment by gmugu** [comment]
这个问题在gpt回答字数越多出现概率越大。tcp都会存在分包的问题，可以考虑使用循环队列缓存数据后进行分包，提高鲁棒性

**Comment by gmugu** [comment]
用了nginx反代了

**Comment by xqdoo00o** [comment]
> 用了nginx反代了

proxy_buffering off;了吗

**Comment by gmugu** [comment]
![image](https://user-images.githubusercontent.com/8317478/230005074-71ab3540-b55f-4990-8226-9c5b367e7cb7.png)
应该是按照要求配置的

**Comment by xqdoo00o** [comment]
> > ![1680680271712](https://user-images.githubusercontent.com/8317478/230001006-260c5b46-2616-4083-9c0f-86dedbffa943.jpg) ![1680680320725](https://user-images.githubusercontent.com/8317478/230001029-a28fa882-473f-4c6d-bd21-fde89864142a.jpg) 我复现了这个问题，并且在代码中加了打印，问题应该出在readChunk()函数，并不是每一次回调的数据都是 "data: {...}\n\n"这样完整的格式
> 
> 使用nginx反代接口了吗

这个OnRecv false 也是打印的data内容吗

**Comment by gmugu** [comment]
> > > ![1680680271712](https://user-images.githubusercontent.com/8317478/230001006-260c5b46-2616-4083-9c0f-86dedbffa943.jpg) ![1680680320725](https://user-images.githubusercontent.com/8317478/230001029-a28fa882-473f-4c6d-bd21-fde89864142a.jpg) 我复现了这个问题，并且在代码中加了打印，问题应该出在readChunk()函数，并不是每一次回调的数据都是 "data: {...}\n\n"这样完整的格式
> > 
> > 
> > 使用nginx反代接口了吗
> 
> 这个OnRecv false 也是打印的data内容吗

不是，在3445行加了这样一句打印：
console.log('onRecv', done, value);

**Comment by xqdoo00o** [comment]
> > > > ![1680680271712](https://user-images.githubusercontent.com/8317478/230001006-260c5b46-2616-4083-9c0f-86dedbffa943.jpg) ![1680680320725](https://user-images.githubusercontent.com/8317478/230001029-a28fa882-473f-4c6d-bd21-fde89864142a.jpg) 我复现了这个问题，并且在代码中加了打印，问题应该出在readChunk()函数，并不是每一次回调的数据都是 "data: {...}\n\n"这样完整的格式
> > > 
> > > 
> > > 使用nginx反代接口了吗
> > 
> > 
> > 这个OnRecv false 也是打印的data内容吗
> 
> 不是，在3445行加了这样一句打印： console.log('onRecv', done, value);

配h2了吗，有https吗，nginx是哪个版本的，我这打印的话，一次只打印一段data

**Comment by gmugu** [comment]
> > > > > ![1680680271712](https://user-images.githubusercontent.com/8317478/230001006-260c5b46-2616-4083-9c0f-86dedbffa943.jpg) ![1680680320725](https://user-images.githubusercontent.com/8317478/230001029-a28fa882-473f-4c6d-bd21-fde89864142a.jpg) 我复现了这个问题，并且在代码中加了打印，问题应该出在readChunk()函数，并不是每一次回调的数据都是 "data: {...}\n\n"这样完整的格式
> > > > 
> > > > 
> > > > 使用nginx反代接口了吗
> > > 
> > > 
> > > 这个OnRecv false 也是打印的data内容吗
> > 
> > 
> > 不是，在3445行加了这样一句打印： console.log('onRecv', done, value);
> 
> 配h2了吗，有https吗，nginx是哪个版本的，我这打印的话，一次只打印一段data

没有h2和https，nginx是1.18.0。tcp是数据流，都要考虑分包问题的

**Comment by xqdoo00o** [comment]
> > > > > > ![1680680271712](https://user-images.githubusercontent.com/8317478/230001006-260c5b46-2616-4083-9c0f-86dedbffa943.jpg) ![1680680320725](https://user-images.githubusercontent.com/8317478/230001029-a28fa882-473f-4c6d-bd21-fde89864142a.jpg) 我复现了这个问题，并且在代码中加了打印，问题应该出在readChunk()函数，并不是每一次回调的数据都是 "data: {...}\n\n"这样完整的格式
> > > > > 
> > > > > 
> > > > > 使用nginx反代接口了吗
> > > > 
> > > > 
> > > > 这个OnRecv false 也是打印的data内容吗
> > > 
> > > 
> > > 不是，在3445行加了这样一句打印： console.log('onRecv', done, value);
> > 
> > 
> > 配h2了吗，有https吗，nginx是哪个版本的，我这打印的话，一次只打印一段data
> 
> 没有h2和https，nginx是1.18.0。tcp是数据流，都要考虑分包问题的

我这打印都是一次只有一条data的，不是你这一次三四个data.
你试试给nginx接口加行配置 chunked_transfer_encoding on;
不行再升级nginx版本到较新的试试

**Comment by gmugu** [comment]
> > > > > > > ![1680680271712](https://user-images.githubusercontent.com/8317478/230001006-260c5b46-2616-4083-9c0f-86dedbffa943.jpg) ![1680680320725](https://user-images.githubusercontent.com/8317478/230001029-a28fa882-473f-4c6d-bd21-fde89864142a.jpg) 我复现了这个问题，并且在代码中加了打印，问题应该出在readChunk()函数，并不是每一次回调的数据都是 "data: {...}\n\n"这样完整的格式
> > > > > > 
> > > > > > 
> > > > > > 使用nginx反代接口了吗
> > > > > 
> > > > > 
> > > > > 这个OnRecv false 也是打印的data内容吗
> > > > 
> > > > 
> > > > 不是，在3445行加了这样一句打印： console.log('onRecv', done, value);
> > > 
> > > 
> > > 配h2了吗，有https吗，nginx是哪个版本的，我这打印的话，一次只打印一段data
> > 
> > 
> > 没有h2和https，nginx是1.18.0。tcp是数据流，都要考虑分包问题的
> 
> 我这打印都是一次只有一条data的，不是你这一次三四个data. 你试试给nginx接口加行配置 chunked_transfer_encoding on 或者off 不行再升级nginx版本到较新的试试

![image](https://user-images.githubusercontent.com/8317478/230055914-cd5d0886-4dcb-473a-ab7f-1230766b6da3.png)
不同网络影响比较大，在公司网络使用的时候没发现，在家里几乎必现。已经通过上面的方式解决

**Comment by xqdoo00o** [comment]
> 

肯定的是，你的nginx buffer有哪里没设置对。
因为你可以看下[初始commit代码](https://github.com/xqdoo00o/chatgpt-web/blob/598d02534f66d55c8be9f467bb13702af5217d3b/chatgpt.html#L567)
我最开始也遇到这个问题，跟你的代码一样 把data最后一部分额外处理。
但是后来nginx加上buffering off就好了，因为这样readchunk一次只有一条data，不需要额外处理了。
能不能按照我上一条说的先试试呢？可能是nginx的bug，也可能是tranfer-encoding的问题

**Comment by xqdoo00o** [comment]
@gmugu  肯定的是，你的nginx buffer有哪里没设置对。
因为你可以看下[初始commit代码](https://github.com/xqdoo00o/chatgpt-web/blob/598d02534f66d55c8be9f467bb13702af5217d3b/chatgpt.html#L567)
我最开始也遇到这个问题，跟你的代码一样 把data最后一部分额外处理。
但是后来nginx加上buffering off就好了，因为这样readchunk一次只有一条data，不需要额外处理了。
能不能按照我上一条说的先试试呢？可能是nginx的bug，也可能是tranfer-encoding的问题

**Comment by gmugu** [comment]
> 

方法试过，不管用

**Comment by gmugu** [comment]
> @gmugu 肯定的是，你的nginx buffer有哪里没设置对。 因为你可以看下[初始commit代码](https://github.com/xqdoo00o/chatgpt-web/blob/598d02534f66d55c8be9f467bb13702af5217d3b/chatgpt.html#L567) 我最开始也遇到这个问题，跟你的代码一样 把data最后一部分额外处理。 但是后来nginx加上buffering off就好了，因为这样readchunk一次只有一条data，不需要额外处理了。 能不能按照我上一条说的先试试呢？可能是nginx的bug，也可能是tranfer-encoding的问题

这个现象出现应该不止我一个，有可能是我哪里配置或版本或网络不对。但是在前端也有必要做一下可靠性处理，损失也不大

**Comment by xqdoo00o** [comment]
> > @gmugu 肯定的是，你的nginx buffer有哪里没设置对。 因为你可以看下[初始commit代码](https://github.com/xqdoo00o/chatgpt-web/blob/598d02534f66d55c8be9f467bb13702af5217d3b/chatgpt.html#L567) 我最开始也遇到这个问题，跟你的代码一样 把data最后一部分额外处理。 但是后来nginx加上buffering off就好了，因为这样readchunk一次只有一条data，不需要额外处理了。 能不能按照我上一条说的先试试呢？可能是nginx的bug，也可能是tranfer-encoding的问题
> 
> 这个现象出现应该不止我一个，有可能是我哪里配置或版本或网络不对。但是在前端也有必要做一下可靠性处理，损失也不大

前端处理只是这一个bug，但是大部分人还是没这个bug的。我试下是不是因为你nginx版本的问题吧

**Comment by gmugu** [comment]
> > > @gmugu 肯定的是，你的nginx buffer有哪里没设置对。 因为你可以看下[初始commit代码](https://github.com/xqdoo00o/chatgpt-web/blob/598d02534f66d55c8be9f467bb13702af5217d3b/chatgpt.html#L567) 我最开始也遇到这个问题，跟你的代码一样 把data最后一部分额外处理。 但是后来nginx加上buffering off就好了，因为这样readchunk一次只有一条data，不需要额外处理了。 能不能按照我上一条说的先试试呢？可能是nginx的bug，也可能是tranfer-encoding的问题
> > 
> > 
> > 这个现象出现应该不止我一个，有可能是我哪里配置或版本或网络不对。但是在前端也有必要做一下可靠性处理，损失也不大
> 
> 能问下你家里的是什么浏览器吗，在公司浏览器也会一次打印三四个data吗 我用nginx 1.18 没复现

公司和家里都是最新版本的edge，用iPhone的Safari也一样。在公司没发现过，今天在家才刚发现的，刚好今天放假，不然能在公司测试测试。公司宽带是电信的，家里是移动的

**Comment by xqdoo00o** [comment]
> > > > @gmugu 肯定的是，你的nginx buffer有哪里没设置对。 因为你可以看下[初始commit代码](https://github.com/xqdoo00o/chatgpt-web/blob/598d02534f66d55c8be9f467bb13702af5217d3b/chatgpt.html#L567) 我最开始也遇到这个问题，跟你的代码一样 把data最后一部分额外处理。 但是后来nginx加上buffering off就好了，因为这样readchunk一次只有一条data，不需要额外处理了。 能不能按照我上一条说的先试试呢？可能是nginx的bug，也可能是tranfer-encoding的问题
> > > 
> > > 
> > > 这个现象出现应该不止我一个，有可能是我哪里配置或版本或网络不对。但是在前端也有必要做一下可靠性处理，损失也不大
> > 
> > 
> > 能问下你家里的是什么浏览器吗，在公司浏览器也会一次打印三四个data吗 我用nginx 1.18 没复现
> 
> 公司和家里都是最新版本的edge，用iPhone的Safari也一样。在公司没发现过，今天在家才刚发现的，刚好今天放假，不然能在公司测试测试。公司宽带是电信的，家里是移动的

猜的可能是移动会劫持http做缓存，可以到公司用电信试试

**Comment by gmugu** [comment]
> > > > > @gmugu 肯定的是，你的nginx buffer有哪里没设置对。 因为你可以看下[初始commit代码](https://github.com/xqdoo00o/chatgpt-web/blob/598d02534f66d55c8be9f467bb13702af5217d3b/chatgpt.html#L567) 我最开始也遇到这个问题，跟你的代码一样 把data最后一部分额外处理。 但是后来nginx加上buffering off就好了，因为这样readchunk一次只有一条data，不需要额外处理了。 能不能按照我上一条说的先试试呢？可能是nginx的bug，也可能是tranfer-encoding的问题
> > > > 
> > > > 
> > > > 这个现象出现应该不止我一个，有可能是我哪里配置或版本或网络不对。但是在前端也有必要做一下可靠性处理，损失也不大
> > > 
> > > 
> > > 能问下你家里的是什么浏览器吗，在公司浏览器也会一次打印三四个data吗 我用nginx 1.18 没复现
> > 
> > 
> > 公司和家里都是最新版本的edge，用iPhone的Safari也一样。在公司没发现过，今天在家才刚发现的，刚好今天放假，不然能在公司测试测试。公司宽带是电信的，家里是移动的
> 
> 猜的可能是移动会劫持http做缓存，可以到公司用电信试试

似乎跟网络有关系，在公司使用一天下来，没发现过分包现象

**Comment by xqdoo00o** [comment]
> > > > > > @gmugu 肯定的是，你的nginx buffer有哪里没设置对。 因为你可以看下[初始commit代码](https://github.com/xqdoo00o/chatgpt-web/blob/598d02534f66d55c8be9f467bb13702af5217d3b/chatgpt.html#L567) 我最开始也遇到这个问题，跟你的代码一样 把data最后一部分额外处理。 但是后来nginx加上buffering off就好了，因为这样readchunk一次只有一条data，不需要额外处理了。 能不能按照我上一条说的先试试呢？可能是nginx的bug，也可能是tranfer-encoding的问题
> > > > > 
> > > > > 
> > > > > 这个现象出现应该不止我一个，有可能是我哪里配置或版本或网络不对。但是在前端也有必要做一下可靠性处理，损失也不大
> > > > 
> > > > 
> > > > 能问下你家里的是什么浏览器吗，在公司浏览器也会一次打印三四个data吗 我用nginx 1.18 没复现
> > > 
> > > 
> > > 公司和家里都是最新版本的edge，用iPhone的Safari也一样。在公司没发现过，今天在家才刚发现的，刚好今天放假，不然能在公司测试测试。公司宽带是电信的，家里是移动的
> > 
> > 
> > 猜的可能是移动会劫持http做缓存，可以到公司用电信试试
> 
> 似乎跟网络有关系，在公司使用一天下来，没发现过分包现象

那应该是移动的问题，上https应该就好了
