### ISSUE TITLE
Question about Default System Role

### ISSUE THREAD

**Issue by yojner** [xqdoo00o/chatgpt-web#90]
Hi, since System Prompt for Default, is set to blank. Is there a way to add your own default system prompt that automatically sets as the default prompt? If yes, which line should I change?

**Comment by xqdoo00o** [comment]
Just add your prompt as value= at line 2332. then you could see that prompt as default system role on top-right quick settings.

**Comment by yojner** [comment]
hi, this is line 2332 on your index.html, can you show how you do it?, like for example if I want to set "You are a helpful assistant" as my default system prompt, how to set it on this line?

 <textarea class="inputTextClass areaTextClass" autocomplete="off"

**Comment by xqdoo00o** [comment]
add `value="You are a helpful assistant"`

**Comment by yojner** [comment]
<textarea class="inputTextClass areaTextClass" autocomplete="off" value="You are a helpful assistant."

like this, right?

**Comment by xqdoo00o** [comment]
yes

**Comment by yojner** [comment]
ok, will try, thank you for your patience.

**Comment by yojner** [comment]
Hi, did what you recommend above but still doesnt appear.

check SS
https://telegra.ph/file/9e8e6f1f5ba04cb33ad6f.jpg

**Comment by xqdoo00o** [comment]
My mistake, plz update to the newest version HTML.
and add your prompt in line **2333** like below fmt
` id="systemInput">You are ChatGPT, a large language model trained by OpenAI. Carefully heed the user's instructions. Respond using markdown.</textarea>`

**Comment by yojner** [comment]
> My mistake, plz update to the newest version HTML. and add your prompt in line **2333** like below fmt ` id="systemInput">You are ChatGPT, a large language model trained by OpenAI. Carefully heed the user's instructions. Respond using markdown.</textarea>`

thanks for fixing this sir, it now appears in the text area, but I noticed when I switched to other prompt, then switch back to the Default again, the default prompt you've made disappear, is that fine?

**Comment by xqdoo00o** [comment]
> 

OK, just undo the modify in line 2333. and update to the newest version HTML.
then add you prompt at line 2924 like below fmt
`"defaultText": "You are ChatGPT, a large language model trained by OpenAI. Carefully heed the user's instructions. Respond using markdown.",`, if you want Chinese default prompt add at line 3077

**Comment by yojner** [comment]
> > 
> 
> OK, just undo the modify in line 2333. and update to the newest version HTML. then add you prompt at line 2924 like below fmt `"defaultText": "You are ChatGPT, a large language model trained by OpenAI. Carefully heed the user's instructions. Respond using markdown.",` if you want Chinese default prompt add at line 3077

hi bro, i think you missed some parts of the code, i re-forked your repo now, and deploy without any changes made yet, it was stuck on the loading screen..

**Comment by xqdoo00o** [comment]
> > > 
> > 
> > 
> > OK, just undo the modify in line 2333. and update to the newest version HTML. then add you prompt at line 2924 like below fmt `"defaultText": "You are ChatGPT, a large language model trained by OpenAI. Carefully heed the user's instructions. Respond using markdown.",` if you want Chinese default prompt add at line 3077
> 
> hi bro, i think you missed some parts of the code when youre doing changes, i re-forked your repo now, and deploy without any changes made yet, it was stuck on the loading screen..

sry, fixed

**Comment by yojner** [comment]
thank you so much sir, everything works fine now.. Time to close :) thank you.
