### ISSUE TITLE
在哪里改反代接口嗷

### ISSUE THREAD

**Issue by lin-1259** [xqdoo00o/chatgpt-web#92]
就是想直接把反代接口写进代码里,就不需要每次打开都需要重新添加了

**Comment by xqdoo00o** [comment]
最新html里，2677行，添加个`value="反代接口"`

**Comment by lw1290537863** [comment]
为什么我用了美国服务器，在魔法上网的时候，是可以验证openai API成功，但不使用魔法的时候，却无法验证API  ？

**Comment by lin-1259** [comment]
> 最新html里，2677行，添加个`value="反代接口"`

好滴好滴，谢谢大佬
