### ISSUE TITLE
写一个冒泡排序，它写出来代码好像没有样式

### ISSUE THREAD

**Issue by xiaociliang** [xqdoo00o/chatgpt-web#93]
它写出来代码好像没有样式，需要调用哪个方法来让样式生效？
![写一个冒泡排序](https://github.com/xqdoo00o/chatgpt-web/assets/6829332/7b008591-a316-4005-b346-78cb62fd6e6c)

**Comment by xqdoo00o** [comment]
未复现，可能是api偶尔会返回的markdown格式不对的原因
![image](https://github.com/xqdoo00o/chatgpt-web/assets/12299238/228cab0b-2b40-4cab-88f3-7dc9e29d0282)

**Comment by xiaociliang** [comment]
那要主动调用哪个方法，让它的样式能够生效？

**Comment by xqdoo00o** [comment]
你可以提问后面加一句，以markdown形式返回代码

**Comment by alading89** [comment]
有可能是反代返回的json被截断
