### ISSUE TITLE
更换语音的问题：如何把英文换成中文？

### ISSUE THREAD

**Issue by lw1290537863** [xqdoo00o/chatgpt-web#96]
![b6eceeb82d97734b85a89f208adcecc](https://github.com/xqdoo00o/chatgpt-web/assets/127683615/72fb27f5-bff9-4c9f-9522-ac8fc8aac6b2)

**Comment by xqdoo00o** [comment]
原始语音接口返回的就是英文额，也没必要单独加翻译吧，因为接口返回是随时可能增删的
