### ISSUE TITLE
建议增加连续会话关联上下文选项

### ISSUE THREAD

**Issue by alading89** [xqdoo00o/chatgpt-web#97]
如果开启连续会话，多问几个问题很容易超出token长度，限制每次会话最大关联上下文语句数，就不会再报错超出token，不需要清除聊天内容
![如图](https://github.com/xqdoo00o/chatgpt-web/assets/75143579/84084f40-9d84-4234-b28b-d2dca6dd01c2)

**Comment by xqdoo00o** [comment]
好了
