### ISSUE TITLE
Separate .env variables

### ISSUE THREAD

**Issue by mxrk314** [xqdoo00o/chatgpt-web#98]
Hi bro, is it possible to make a separate .env variables for the apiEndpoint and apiKey values? so that you wont need to include these into the index.html?

I am planning to get rid of the placeholders for endpoint and key, and add my pre-configured setup, but i dont want to expose my key and endpoint in the html

anyway, tnx for your new update!

**Comment by xqdoo00o** [comment]
Added, add a new file `env.js` under the same directory of index.html, example
```
envAPIEndpoint="https://api.openai.com/"
envAPIKey="sk-your-token"
```

**Comment by mxrk314** [comment]
ill try, thank you so much bro

**Comment by Nriver** [comment]
Cool!

**Comment by mxrk314** [comment]
hello bro, the env.js works, the thing is it still exposes your endpoint and key when check in the browser'sw developers option, see image !(https://memos.renj.dev/o/r/1/427657b8-ef92-4ce5-9289-fc73f9b5b6a9/IMG_20230718_153411.jpg)

**Comment by mxrk314** [comment]
ill close this one now, thank you for this update sir/bro..
